[2019-02-14 00:30:05] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 20974
[2019-02-14 00:30:06] INFO [django.server.log_message:124] "GET /static/Projects/custom/css/projects.css HTTP/1.1" 200 9811
[2019-02-14 00:30:06] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/newstylenew.css HTTP/1.1" 200 7655
[2019-02-14 00:30:06] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-02-14 00:30:06] WARNING [django.server.log_message:124] "GET /images/icon5.png HTTP/1.1" 404 12560
[2019-02-14 00:36:56] ERROR [django.request.log_response:228] Internal Server Error: /projects/
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\Projects\views.py", line 22, in project_index
    return render(request, 'projects/index.html', context)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 111: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
[2019-02-14 00:36:56] ERROR [django.server.log_message:124] "GET /projects/ HTTP/1.1" 500 181660
[2019-02-14 00:42:05] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 20974
[2019-02-14 00:42:05] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-02-14 00:42:05] WARNING [django.server.log_message:124] "GET /images/icon5.png HTTP/1.1" 404 12560
[2019-02-14 07:34:58] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 10902
[2019-02-14 07:34:59] INFO [django.server.log_message:124] "GET /static/Projects/custom/css/projects.css HTTP/1.1" 304 0
[2019-02-14 07:34:59] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 07:34:59] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14344
[2019-02-14 07:34:59] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/newstylenew.css HTTP/1.1" 304 0
[2019-02-14 08:05:00] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 20974
[2019-02-14 08:05:01] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-02-14 08:05:01] WARNING [django.server.log_message:124] "GET /images/icon5.png HTTP/1.1" 404 12560
[2019-02-14 08:05:07] WARNING [django.request.log_response:228] Not Found: /favicon.ico
[2019-02-14 08:05:07] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 12545
[2019-02-14 08:05:08] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 11294
[2019-02-14 08:05:08] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:05:08] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14344
[2019-02-14 08:05:19] INFO [django.server.log_message:124] "GET /admin HTTP/1.1" 302 0
[2019-02-14 08:05:20] INFO [django.server.log_message:124] "GET /admin/login/?next=/admin HTTP/1.1" 200 1817
[2019-02-14 08:05:20] INFO [django.server.log_message:124] "GET /static/admin/css/login.css HTTP/1.1" 200 1281
[2019-02-14 08:05:20] INFO [django.server.log_message:124] "GET /static/admin/css/base.css HTTP/1.1" 200 17084
[2019-02-14 08:05:20] INFO [django.server.log_message:124] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18884
[2019-02-14 08:05:21] INFO [django.server.log_message:124] "GET /static/admin/css/fonts.css HTTP/1.1" 200 443
[2019-02-14 08:05:21] INFO [django.server.log_message:124] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[2019-02-14 08:05:21] INFO [django.server.log_message:124] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[2019-02-14 08:05:24] INFO [django.server.log_message:124] "POST /admin/login/?next=/admin HTTP/1.1" 200 1980
[2019-02-14 08:05:25] INFO [django.server.log_message:124] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[2019-02-14 08:05:32] INFO [django.server.log_message:124] "POST /admin/login/?next=/admin HTTP/1.1" 302 0
[2019-02-14 08:05:32] INFO [django.server.log_message:124] "GET /admin HTTP/1.1" 200 26238
[2019-02-14 08:05:33] INFO [django.server.log_message:124] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 439
[2019-02-14 08:05:33] INFO [django.server.log_message:124] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 383
[2019-02-14 08:05:33] INFO [django.server.log_message:124] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 334
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /admin/Projects/project/ HTTP/1.1" 200 3187
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6514
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 371
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 7078
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1580
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/core.js HTTP/1.1" 200 7346
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 131128
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 268490
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8918
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/js/actions.js HTTP/1.1" 200 6655
[2019-02-14 08:05:48] INFO [django.server.log_message:124] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 334
[2019-02-14 08:05:51] INFO [django.server.log_message:124] "GET /admin/Projects/project/add/ HTTP/1.1" 200 6138
[2019-02-14 08:05:51] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:05:51] INFO [django.server.log_message:124] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 505
[2019-02-14 08:05:51] INFO [django.server.log_message:124] "GET /static/admin/js/change_form.js HTTP/1.1" 200 732
[2019-02-14 08:05:52] INFO [django.server.log_message:124] "GET /static/admin/css/forms.css HTTP/1.1" 200 8688
[2019-02-14 08:05:52] INFO [django.server.log_message:124] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10905
[2019-02-14 08:06:47] INFO [django.server.log_message:124] "POST /admin/Projects/project/add/ HTTP/1.1" 302 0
[2019-02-14 08:06:47] INFO [django.server.log_message:124] "GET /admin/Projects/project/ HTTP/1.1" 200 4537
[2019-02-14 08:06:47] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:06:47] INFO [django.server.log_message:124] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 439
[2019-02-14 08:06:51] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13294
[2019-02-14 08:06:51] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:06:51] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14344
[2019-02-14 08:06:52] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 200 520020
[2019-02-14 08:06:57] ERROR [django.request.log_response:228] Internal Server Error: /projects/projects/1
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\Projects\views.py", line 46, in project_courses
    project = Project.objects.get(project_title=project_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
Projects.models.Project.DoesNotExist: Project matching query does not exist.
[2019-02-14 08:06:57] ERROR [django.server.log_message:124] "GET /projects/projects/1 HTTP/1.1" 500 79533
[2019-02-14 08:07:48] ERROR [django.request.log_response:228] Internal Server Error: /projects/projects/DevOps
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\Projects\views.py", line 56, in project_courses
    return render(request, 'projects/project_courses.html', context)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
[2019-02-14 08:07:48] ERROR [django.server.log_message:124] "GET /projects/projects/DevOps HTTP/1.1" 500 173368
[2019-02-14 08:07:55] ERROR [django.request.log_response:228] Internal Server Error: /projects/DevOps
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: project_course_topics() got an unexpected keyword argument 'course_name'
[2019-02-14 08:07:55] ERROR [django.server.log_message:124] "GET /projects/DevOps HTTP/1.1" 500 72268
[2019-02-14 08:08:03] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13294
[2019-02-14 08:08:04] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:08:04] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14344
[2019-02-14 08:08:04] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 08:08:05] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:08:05] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14344
[2019-02-14 08:08:08] ERROR [django.request.log_response:228] Internal Server Error: /projects/projects/1
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\Projects\views.py", line 46, in project_courses
    project = Project.objects.get(project_title=project_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
Projects.models.Project.DoesNotExist: Project matching query does not exist.
[2019-02-14 08:08:08] ERROR [django.server.log_message:124] "GET /projects/projects/1 HTTP/1.1" 500 79534
[2019-02-14 08:13:10] ERROR [django.request.log_response:228] Internal Server Error: /projects/projects/1
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: project_courses() got an unexpected keyword argument 'project_name'
[2019-02-14 08:13:10] ERROR [django.server.log_message:124] "GET /projects/projects/1 HTTP/1.1" 500 67657
[2019-02-14 08:15:56] WARNING [django.request.log_response:228] Not Found: /projects/projects/1
[2019-02-14 08:15:56] WARNING [django.server.log_message:124] "GET /projects/projects/1 HTTP/1.1" 404 14120
[2019-02-14 08:17:52] WARNING [django.request.log_response:228] Not Found: /projects/projects/1
[2019-02-14 08:17:52] WARNING [django.server.log_message:124] "GET /projects/projects/1 HTTP/1.1" 404 14120
[2019-02-14 08:17:58] ERROR [django.request.log_response:228] Internal Server Error: /projects/1
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: project_course_topics() got an unexpected keyword argument 'course_name'
[2019-02-14 08:17:58] ERROR [django.server.log_message:124] "GET /projects/1 HTTP/1.1" 500 72359
[2019-02-14 08:18:15] ERROR [django.request.log_response:228] Internal Server Error: /projects/1/course
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\Projects\views.py", line 56, in project_courses
    return render(request, 'projects/project_courses.html', context)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
[2019-02-14 08:18:15] ERROR [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 500 173191
[2019-02-14 08:22:23] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13292
[2019-02-14 08:22:24] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:22:24] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:22:24] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 08:22:27] ERROR [django.request.log_response:228] Internal Server Error: /projects/1/course
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\Projects\views.py", line 56, in project_courses
    return render(request, 'projects/project_courses.html', context)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
[2019-02-14 08:22:27] ERROR [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 500 173171
[2019-02-14 08:24:38] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 12714
[2019-02-14 08:24:38] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:24:38] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:24:58] INFO [django.server.log_message:124] "GET /admin/Projects/ HTTP/1.1" 200 5366
[2019-02-14 08:25:14] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 3234
[2019-02-14 08:25:14] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:25:17] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/add/ HTTP/1.1" 200 9107
[2019-02-14 08:25:17] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:27:11] INFO [django.server.log_message:124] "POST /admin/Projects/projectcourse/add/ HTTP/1.1" 302 0
[2019-02-14 08:27:12] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 4619
[2019-02-14 08:27:12] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:27:18] INFO [django.server.log_message:124] "GET /admin/Projects/ HTTP/1.1" 200 5366
[2019-02-14 08:27:20] INFO [django.server.log_message:124] "GET /admin/Projects/project/ HTTP/1.1" 200 4353
[2019-02-14 08:27:20] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:27:23] INFO [django.server.log_message:124] "GET /admin/Projects/project/1/change/ HTTP/1.1" 200 6582
[2019-02-14 08:27:23] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:27:44] INFO [django.server.log_message:124] "POST /admin/Projects/project/1/change/ HTTP/1.1" 302 0
[2019-02-14 08:27:44] INFO [django.server.log_message:124] "GET /admin/Projects/project/ HTTP/1.1" 200 4539
[2019-02-14 08:27:44] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:27:48] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 13769
[2019-02-14 08:27:48] INFO [django.server.log_message:124] "GET /media/project/GDG-Ogbomoso.png HTTP/1.1" 200 18686
[2019-02-14 08:27:48] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:27:48] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:27:58] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:27:58] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:27:58] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:27:58] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 08:27:58] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:28:04] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 13769
[2019-02-14 08:28:04] INFO [django.server.log_message:124] "GET /media/project/GDG-Ogbomoso.png HTTP/1.1" 304 0
[2019-02-14 08:28:04] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:28:04] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:36:11] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 11934
[2019-02-14 08:36:13] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 11934
[2019-02-14 08:36:14] WARNING [django.request.log_response:228] Not Found: /projects/1/project/GDG-Ogbomoso.png
[2019-02-14 08:36:14] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:36:14] WARNING [django.server.log_message:124] "GET /projects/1/project/GDG-Ogbomoso.png HTTP/1.1" 404 14168
[2019-02-14 08:36:14] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:36:40] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 11934
[2019-02-14 08:36:40] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:36:41] WARNING [django.request.log_response:228] Not Found: /projects/1/project/GDG-Ogbomoso.png
[2019-02-14 08:36:41] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:36:41] WARNING [django.server.log_message:124] "GET /projects/1/project/GDG-Ogbomoso.png HTTP/1.1" 404 14168
[2019-02-14 08:36:55] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 11934
[2019-02-14 08:36:56] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:36:56] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:36:56] WARNING [django.request.log_response:228] Not Found: /projects/1/project/GDG-Ogbomoso.png
[2019-02-14 08:36:56] WARNING [django.server.log_message:124] "GET /projects/1/project/GDG-Ogbomoso.png HTTP/1.1" 404 14168
[2019-02-14 08:37:53] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 12398
[2019-02-14 08:37:53] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:37:53] INFO [django.server.log_message:124] "GET /media/project/GDG-Ogbomoso.png HTTP/1.1" 304 0
[2019-02-14 08:37:53] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:37:59] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:37:59] INFO [django.server.log_message:124] "GET /login/?next=/projects/course/1/topics/1 HTTP/1.1" 200 3467
[2019-02-14 08:37:59] INFO [django.server.log_message:124] "GET /static/home/css/styles.css HTTP/1.1" 200 7692
[2019-02-14 08:38:00] INFO [django.server.log_message:124] "GET /static/home/images/imgback.jpg HTTP/1.1" 200 1032219
[2019-02-14 08:38:15] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:38:15] INFO [django.server.log_message:124] "GET /login/?next=/projects/course/1/topics/1 HTTP/1.1" 200 3467
[2019-02-14 08:38:33] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:38:33] INFO [django.server.log_message:124] "GET /login/?next=/projects/course/1/topics/1 HTTP/1.1" 200 3467
[2019-02-14 08:38:42] INFO [django.server.log_message:124] "POST /login/?next=/projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:38:42] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:38:42] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:38:43] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:38:43] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:38:43] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 08:38:47] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 13769
[2019-02-14 08:38:47] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:38:47] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:38:50] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:38:50] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:38:50] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:38:50] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:38:54] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 13769
[2019-02-14 08:38:54] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:38:54] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:39:16] INFO [django.server.log_message:124] "GET /admin/Projects/ HTTP/1.1" 200 5366
[2019-02-14 08:39:19] INFO [django.server.log_message:124] "GET /admin/Projects/projectcoursetopic/ HTTP/1.1" 200 3274
[2019-02-14 08:39:19] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:39:23] INFO [django.server.log_message:124] "GET /admin/Projects/ HTTP/1.1" 200 5366
[2019-02-14 08:39:25] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 4421
[2019-02-14 08:39:25] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:39:27] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/add/ HTTP/1.1" 200 9107
[2019-02-14 08:39:28] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:40:44] INFO [django.server.log_message:124] "POST /admin/Projects/projectcourse/add/ HTTP/1.1" 302 0
[2019-02-14 08:40:44] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 4849
[2019-02-14 08:40:44] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:40:46] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14881
[2019-02-14 08:40:47] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:40:47] INFO [django.server.log_message:124] "GET /media/project/GDG-Ogbomoso.png HTTP/1.1" 304 0
[2019-02-14 08:40:47] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:40:47] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 200 94223
[2019-02-14 08:41:33] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/2/change/ HTTP/1.1" 200 9645
[2019-02-14 08:41:33] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:41:38] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 4651
[2019-02-14 08:41:38] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:41:40] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/2/change/ HTTP/1.1" 200 9645
[2019-02-14 08:41:40] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:41:41] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 4651
[2019-02-14 08:41:41] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:41:43] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/1/change/ HTTP/1.1" 200 9594
[2019-02-14 08:41:43] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:41:57] INFO [django.server.log_message:124] "POST /admin/Projects/projectcourse/1/change/ HTTP/1.1" 302 0
[2019-02-14 08:41:57] INFO [django.server.log_message:124] "GET /admin/Projects/projectcourse/ HTTP/1.1" 200 4851
[2019-02-14 08:41:57] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:41:59] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14877
[2019-02-14 08:41:59] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:41:59] INFO [django.server.log_message:124] "GET /media/project/Dprince_.png HTTP/1.1" 200 44690
[2019-02-14 08:41:59] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:41:59] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 304 0
[2019-02-14 08:44:48] INFO [django.server.log_message:124] "GET /admin/ HTTP/1.1" 200 27759
[2019-02-14 08:44:52] INFO [django.server.log_message:124] "GET /admin/users/customuser/ HTTP/1.1" 200 6370
[2019-02-14 08:44:52] ERROR [django.server.log_message:124] "GET /admin/users/customuser/ HTTP/1.1" 500 59
[2019-02-14 08:44:52] INFO [django.server.log_message:124] "GET /admin/users/customuser/ HTTP/1.1" 200 6370
[2019-02-14 08:44:52] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:44:52] INFO [django.server.log_message:124] "GET /static/admin/img/search.svg HTTP/1.1" 200 461
[2019-02-14 08:44:53] INFO [django.server.log_message:124] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1116
[2019-02-14 08:44:55] INFO [django.server.log_message:124] "GET /admin/users/customuser/1/change/ HTTP/1.1" 200 30561
[2019-02-14 08:44:55] INFO [django.server.log_message:124] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5899
[2019-02-14 08:44:55] INFO [django.server.log_message:124] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7985
[2019-02-14 08:44:55] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12932
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20709
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3325
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 658
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 658
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1095
[2019-02-14 08:44:56] INFO [django.server.log_message:124] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 686
[2019-02-14 08:45:03] INFO [django.server.log_message:124] "POST /admin/users/customuser/1/change/ HTTP/1.1" 302 0
[2019-02-14 08:45:04] INFO [django.server.log_message:124] "GET /admin/users/customuser/ HTTP/1.1" 200 6568
[2019-02-14 08:45:04] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 08:45:09] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 08:45:10] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:45:10] INFO [django.server.log_message:124] "GET /media/project/Dprince_.png HTTP/1.1" 304 0
[2019-02-14 08:45:10] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:45:10] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 304 0
[2019-02-14 08:45:12] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:45:12] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:45:12] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:45:12] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 08:45:12] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:45:15] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 08:45:16] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:45:16] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:45:30] INFO [django.server.log_message:124] "GET /projects/course/2/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:45:30] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:45:30] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:45:30] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:46:05] INFO [django.server.log_message:124] "GET /projects/course/2/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:46:05] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:46:05] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:46:05] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:47:00] INFO [django.server.log_message:124] "GET /workexperience/ HTTP/1.1" 200 19244
[2019-02-14 08:47:00] WARNING [django.request.log_response:228] Not Found: /workexperience/images/icon5.png
[2019-02-14 08:47:00] WARNING [django.server.log_message:124] "GET /workexperience/images/icon5.png HTTP/1.1" 404 13374
[2019-02-14 08:47:02] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/aboutrec.png HTTP/1.1" 200 590531
[2019-02-14 08:47:02] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok.png HTTP/1.1" 200 281569
[2019-02-14 08:47:12] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 08:59:17] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:59:17] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:59:17] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 08:59:17] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:59:20] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 08:59:20] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:59:20] INFO [django.server.log_message:124] "GET /media/project/Dprince_.png HTTP/1.1" 304 0
[2019-02-14 08:59:20] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 08:59:20] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 304 0
[2019-02-14 08:59:31] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 08:59:31] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 08:59:32] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 08:59:32] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 14138
[2019-02-14 08:59:34] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 08:59:35] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 08:59:35] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 14144
[2019-02-14 09:00:38] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:00:39] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:00:39] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:00:42] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 09:00:42] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 09:00:42] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 09:00:42] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 13936
[2019-02-14 09:01:52] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:01:53] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:01:53] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:01:53] INFO [django.server.log_message:124] "GET /media/project/Dprince_.png HTTP/1.1" 304 0
[2019-02-14 09:01:53] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 304 0
[2019-02-14 09:06:56] INFO [django.server.log_message:124] "GET /admin/users/customuser/1/change/ HTTP/1.1" 200 30561
[2019-02-14 09:06:56] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 09:07:10] INFO [django.server.log_message:124] "POST /admin/users/customuser/1/change/ HTTP/1.1" 302 0
[2019-02-14 09:07:10] INFO [django.server.log_message:124] "GET /admin/users/customuser/ HTTP/1.1" 200 6568
[2019-02-14 09:07:10] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 09:07:31] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:07:32] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:07:32] INFO [django.server.log_message:124] "GET /media/project/Dprince_.png HTTP/1.1" 304 0
[2019-02-14 09:07:32] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:07:32] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 304 0
[2019-02-14 09:07:35] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 09:07:35] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 09:07:35] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 09:07:35] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 13936
[2019-02-14 09:07:35] INFO [django.server.log_message:124] "GET /media/project/0_raqypaa_HCO12MFq.png HTTP/1.1" 304 0
[2019-02-14 09:07:38] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:07:38] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:07:38] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:10:47] INFO [django.server.log_message:124] "GET /admin/users/customuser/1/change/ HTTP/1.1" 302 0
[2019-02-14 09:10:48] INFO [django.server.log_message:124] "GET /admin/login/?next=/admin/users/customuser/1/change/ HTTP/1.1" 200 1871
[2019-02-14 09:10:51] INFO [django.server.log_message:124] "POST /admin/login/?next=/admin/users/customuser/1/change/ HTTP/1.1" 200 2034
[2019-02-14 09:11:03] INFO [django.server.log_message:124] "POST /admin/login/?next=/admin/users/customuser/1/change/ HTTP/1.1" 302 0
[2019-02-14 09:11:04] INFO [django.server.log_message:124] "GET /admin/users/customuser/1/change/ HTTP/1.1" 200 32649
[2019-02-14 09:11:04] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 09:11:25] INFO [django.server.log_message:124] "POST /admin/users/customuser/1/change/ HTTP/1.1" 302 0
[2019-02-14 09:11:25] INFO [django.server.log_message:124] "GET /admin/users/customuser/ HTTP/1.1" 200 6568
[2019-02-14 09:11:25] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 09:11:34] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:11:34] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:11:34] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:11:34] INFO [django.server.log_message:124] "GET /media/project/Dprince_.png HTTP/1.1" 304 0
[2019-02-14 09:11:34] INFO [django.server.log_message:124] "GET /media/project/futuristic_dark_web_mesh.jpg HTTP/1.1" 304 0
[2019-02-14 09:11:40] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 09:11:40] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 09:11:40] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 09:11:40] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 13936
[2019-02-14 09:11:52] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:11:52] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:11:52] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:12:22] WARNING [django.request.log_response:228] Not Found: /coure/1/topics/1
[2019-02-14 09:12:22] WARNING [django.server.log_message:124] "GET /coure/1/topics/1 HTTP/1.1" 404 12560
[2019-02-14 09:12:30] WARNING [django.request.log_response:228] Not Found: /course/1/topics/1
[2019-02-14 09:12:30] WARNING [django.server.log_message:124] "GET /course/1/topics/1 HTTP/1.1" 404 12563
[2019-02-14 09:12:41] INFO [django.server.log_message:124] "GET /projects/course/1/topics/1 HTTP/1.1" 302 0
[2019-02-14 09:12:41] INFO [django.server.log_message:124] "GET /projects/ HTTP/1.1" 200 13305
[2019-02-14 09:12:41] WARNING [django.request.log_response:228] Not Found: /projects/images/icon5.png
[2019-02-14 09:12:41] WARNING [django.server.log_message:124] "GET /projects/images/icon5.png HTTP/1.1" 404 13936
[2019-02-14 09:12:46] INFO [django.server.log_message:124] "GET /projects/1/course HTTP/1.1" 200 14875
[2019-02-14 09:12:46] WARNING [django.request.log_response:228] Not Found: /projects/1/images/icon5.png
[2019-02-14 09:12:46] WARNING [django.server.log_message:124] "GET /projects/1/images/icon5.png HTTP/1.1" 404 13942
[2019-02-14 09:20:28] INFO [django.server.log_message:124] "GET /workexperience/ HTTP/1.1" 200 19244
[2019-02-14 09:20:29] WARNING [django.request.log_response:228] Not Found: /workexperience/images/icon5.png
[2019-02-14 09:20:29] WARNING [django.server.log_message:124] "GET /workexperience/images/icon5.png HTTP/1.1" 404 13374
[2019-02-14 09:20:29] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:22:48] INFO [django.server.log_message:124] "GET /workexperience/ HTTP/1.1" 200 19355
[2019-02-14 09:22:48] WARNING [django.request.log_response:228] Not Found: /workexperience/images/icon5.png
[2019-02-14 09:22:48] WARNING [django.server.log_message:124] "GET /workexperience/images/icon5.png HTTP/1.1" 404 13374
[2019-02-14 09:22:49] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:11] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:12] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:12] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:17] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:18] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:18] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:18] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:18] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:19] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:19] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:19] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:19] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:19] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:20] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:20] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:20] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:20] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:20] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:20] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:21] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:21] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:21] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:21] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:21] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:22] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:24] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:40:43] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs//aboutrec.png HTTP/1.1" 304 0
[2019-02-14 09:40:52] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:41:14] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:41:15] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:41:15] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:42:20] INFO [django.server.log_message:124] "GET /workexperience/ HTTP/1.1" 200 17846
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js HTTP/1.1" 304 0
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/js/validation/jquery.validate.js HTTP/1.1" 304 0
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/css/bootstrap.min.css HTTP/1.1" 304 0
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/style.css HTTP/1.1" 304 0
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/css/style.css HTTP/1.1" 304 0
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/newstyle2.css HTTP/1.1" 200 142808
[2019-02-14 09:42:21] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/main.css HTTP/1.1" 200 811
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/home/images/logo.png HTTP/1.1" 304 0
[2019-02-14 09:42:22] WARNING [django.request.log_response:228] Not Found: /workexperience/images/icon5.png
[2019-02-14 09:42:22] WARNING [django.server.log_message:124] "GET /workexperience/images/icon5.png HTTP/1.1" 404 13374
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/js/bootstrap.min.js HTTP/1.1" 304 0
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/faq/js/jquery-2.1.1.js HTTP/1.1" 304 0
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/faq/js/main.js HTTP/1.1" 304 0
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/faq/js/jquery.mobile.custom.min.js HTTP/1.1" 304 0
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/js/waterbubble.js HTTP/1.1" 304 0
[2019-02-14 09:42:22] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/fonts/fontsstylesheet.css HTTP/1.1" 304 0
[2019-02-14 09:42:23] INFO [django.server.log_message:124] "GET /static/home/images/aoc.png HTTP/1.1" 304 0
[2019-02-14 09:42:23] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/radio1.png HTTP/1.1" 304 0
[2019-02-14 09:42:23] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:42:23] INFO [django.server.log_message:124] "GET /static/home/images/graduate.png HTTP/1.1" 304 0
[2019-02-14 09:42:23] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/womann.jpg HTTP/1.1" 304 0
[2019-02-14 09:42:23] INFO [django.server.log_message:124] "GET /static/home/images/prooo.png HTTP/1.1" 304 0
[2019-02-14 09:50:31] INFO [django.server.log_message:124] "GET /workexperience/ HTTP/1.1" 200 17952
[2019-02-14 09:50:31] WARNING [django.request.log_response:228] Not Found: /workexperience/images/icon5.png
[2019-02-14 09:50:31] WARNING [django.server.log_message:124] "GET /workexperience/images/icon5.png HTTP/1.1" 404 13374
[2019-02-14 09:50:32] WARNING [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs/wok-sm.png HTTP/1.1" 404 1846
[2019-02-14 09:51:34] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3406
[2019-02-14 09:51:43] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2019-02-14 09:51:44] INFO [django.server.log_message:124] "GET /courses/userinterest HTTP/1.1" 200 17425
[2019-02-14 09:51:44] WARNING [django.request.log_response:228] Not Found: /courses/images/icon5.png
[2019-02-14 09:51:44] WARNING [django.server.log_message:124] "GET /courses/images/icon5.png HTTP/1.1" 404 15527
[2019-02-14 09:51:44] INFO [django.server.log_message:124] "GET /static/home/images/icon1.png HTTP/1.1" 304 0
[2019-02-14 09:51:44] INFO [django.server.log_message:124] "GET /static/home/images/logout1.png HTTP/1.1" 304 0
[2019-02-14 09:51:44] INFO [django.server.log_message:124] "GET /static/home/images/lin-logo.png HTTP/1.1" 200 9301
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/button-left.png HTTP/1.1" 200 2071
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/amazons.png HTTP/1.1" 200 10409
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/ppt.png HTTP/1.1" 200 964
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/jjava.png HTTP/1.1" 200 10506
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/rchsaa.png HTTP/1.1" 200 6733
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/ajs.png HTTP/1.1" 200 6757
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/imgs//list-bg.png HTTP/1.1" 200 279917
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/csecurity.png HTTP/1.1" 200 5664
[2019-02-14 09:51:45] INFO [django.server.log_message:124] "GET /static/home/images/biz.png HTTP/1.1" 200 7859
[2019-02-14 09:51:46] INFO [django.server.log_message:124] "GET /static/home/images/dba.png HTTP/1.1" 200 5461
[2019-02-14 09:51:46] INFO [django.server.log_message:124] "GET /static/home/images/py.png HTTP/1.1" 200 5447
[2019-02-14 09:52:04] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16597
[2019-02-14 09:52:05] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 09:52:05] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 09:52:05] INFO [django.server.log_message:124] "GET /static/home/images/bannerr.png HTTP/1.1" 304 0
[2019-02-14 10:03:28] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16885
[2019-02-14 10:03:29] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 10:03:29] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 10:04:02] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16884
[2019-02-14 10:04:03] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 10:04:03] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 10:04:20] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16884
[2019-02-14 10:04:20] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 10:04:21] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 10:05:52] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16921
[2019-02-14 10:05:53] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 10:05:53] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 10:06:12] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16921
[2019-02-14 10:06:12] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 10:06:12] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 10:16:01] INFO [django.server.log_message:124] "GET /user/account/settings HTTP/1.1" 200 16920
[2019-02-14 10:16:02] WARNING [django.request.log_response:228] Not Found: /user/account/images/icon5.png
[2019-02-14 10:16:02] WARNING [django.server.log_message:124] "GET /user/account/images/icon5.png HTTP/1.1" 404 12599
[2019-02-14 10:19:48] ERROR [django.request.log_response:228] Internal Server Error: /user/account/ec2dashboard/
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\home\views.py", line 961, in ec2dashboard
    awscred = AwsCredential.objects.get(user = request.user)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
home.models.AwsCredential.DoesNotExist: AwsCredential matching query does not exist.
[2019-02-14 10:19:48] ERROR [django.server.log_message:124] "GET /user/account/ec2dashboard/ HTTP/1.1" 500 79333
[2019-02-14 11:11:48] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 20974
[2019-02-14 11:11:49] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-02-14 11:11:49] WARNING [django.server.log_message:124] "GET /images/icon5.png HTTP/1.1" 404 12560
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/views.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/linuxx.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/awssa.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/java.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/btns.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/pupett.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/placement.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/experience.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/pupet.png HTTP/1.1" 304 0
[2019-02-14 11:11:49] INFO [django.server.log_message:124] "GET /static/home/images/training.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/engine2.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/tutor.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/q1.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/44.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/22.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/q2.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/33.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/dre.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/kid.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/hotels.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/hotelsafrica.png HTTP/1.1" 304 0
[2019-02-14 11:11:50] INFO [django.server.log_message:124] "GET /static/home/images/ontario.png HTTP/1.1" 304 0
[2019-02-14 11:12:00] INFO [django.server.log_message:124] "GET /workexperience/ HTTP/1.1" 200 17952
[2019-02-14 11:12:01] WARNING [django.request.log_response:228] Not Found: /workexperience/images/icon5.png
[2019-02-14 11:12:01] WARNING [django.server.log_message:124] "GET /workexperience/images/icon5.png HTTP/1.1" 404 13374
[2019-02-14 11:12:06] INFO [django.server.log_message:124] "GET /workexperience/pay/ HTTP/1.1" 302 0
[2019-02-14 11:12:06] INFO [django.server.log_message:124] "GET /login/?next=/workexperience/pay/ HTTP/1.1" 200 3453
[2019-02-14 11:12:15] INFO [django.server.log_message:124] "POST /login/?next=/workexperience/pay/ HTTP/1.1" 302 0
[2019-02-14 11:12:15] ERROR [django.request.log_response:228] Internal Server Error: /workexperience/pay/
Traceback (most recent call last):
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\makinde\Documents\Projects\Wrk\linuxjobber2\Django\Linuxjobber\home\views.py", line 563, in pay
    stripe.api_key = stripeset[0].secretkey
  File "C:\Users\makinde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2019-02-14 11:12:15] ERROR [django.server.log_message:124] "GET /workexperience/pay/ HTTP/1.1" 500 80412
[2019-02-14 11:12:26] INFO [django.server.log_message:124] "GET /admin/ HTTP/1.1" 200 28668
[2019-02-14 11:12:31] INFO [django.server.log_message:124] "GET /admin/home/stripepayment/ HTTP/1.1" 200 3218
[2019-02-14 11:12:31] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 11:12:41] INFO [django.server.log_message:124] "GET /admin/home/stripepayment/add/ HTTP/1.1" 200 5068
[2019-02-14 11:12:41] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 11:13:18] INFO [django.server.log_message:124] "POST /admin/home/stripepayment/add/ HTTP/1.1" 302 0
[2019-02-14 11:13:18] INFO [django.server.log_message:124] "GET /admin/home/stripepayment/ HTTP/1.1" 200 4645
[2019-02-14 11:13:19] INFO [django.server.log_message:124] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[2019-02-14 11:13:26] INFO [django.server.log_message:124] "GET /login/?next=/workexperience/pay/ HTTP/1.1" 200 3453
[2019-02-14 11:13:34] INFO [django.server.log_message:124] "POST /login/?next=/workexperience/pay/ HTTP/1.1" 302 0
[2019-02-14 11:13:34] INFO [django.server.log_message:124] "GET /workexperience/pay/ HTTP/1.1" 200 23420
[2019-02-14 11:13:35] WARNING [django.request.log_response:228] Not Found: /workexperience/pay/images/icon5.png
[2019-02-14 11:13:35] WARNING [django.server.log_message:124] "GET /workexperience/pay/images/icon5.png HTTP/1.1" 404 13386
[2019-02-14 11:25:44] INFO [django.server.log_message:124] "GET /workexperience/pay/ HTTP/1.1" 200 23420
[2019-02-14 11:25:44] WARNING [django.request.log_response:228] Not Found: /workexperience/pay/images/icon5.png
[2019-02-14 11:25:44] WARNING [django.server.log_message:124] "GET /workexperience/pay/images/icon5.png HTTP/1.1" 404 13386
[2019-02-14 11:27:09] INFO [django.server.log_message:124] "GET /workexperience/pay/ HTTP/1.1" 200 23395
[2019-02-14 11:27:09] WARNING [django.request.log_response:228] Not Found: /workexperience/pay/images/icon5.png
[2019-02-14 11:27:09] WARNING [django.server.log_message:124] "GET /workexperience/pay/images/icon5.png HTTP/1.1" 404 13386
[2019-02-14 11:28:52] INFO [django.server.log_message:124] "GET /workexperience/pay/ HTTP/1.1" 200 23448
[2019-02-14 11:28:52] WARNING [django.request.log_response:228] Not Found: /workexperience/pay/images/icon5.png
[2019-02-14 11:28:52] WARNING [django.server.log_message:124] "GET /workexperience/pay/images/icon5.png HTTP/1.1" 404 13386
[2019-02-14 11:38:24] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 22398
[2019-02-14 11:38:25] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/newstylenew.css HTTP/1.1" 304 0
[2019-02-14 11:38:25] INFO [django.server.log_message:124] "GET /static/Projects/custom/css/projects.css HTTP/1.1" 304 0
[2019-02-14 11:38:25] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-02-14 11:38:25] WARNING [django.server.log_message:124] "GET /images/icon5.png HTTP/1.1" 404 12560
[2019-02-14 11:38:29] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/images/bannerr.png HTTP/1.1" 304 0
