[2019-04-07 22:14:08] WARNING [django.request.get_response:93] Not Found: /robots.txt
[2019-04-07 22:14:08] WARNING [django.channels.server.log_action:149] [33mHTTP GET /robots.txt 404 [0.19, 127.0.0.1:39052][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [1.22, 127.0.0.1:39050][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/css/newstylenew.css 304 [0.02, 127.0.0.1:39056][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/css/main.css 304 [0.01, 127.0.0.1:39056][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/Projects/custom/css/projects.css 304 [0.03, 127.0.0.1:39056][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/css/style.css 200 [0.11, 127.0.0.1:39052][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/css/bootstrap.min.css 200 [0.14, 127.0.0.1:39050][0m
[2019-04-07 22:14:09] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/newstyle2.css 200 [0.14, 127.0.0.1:39054][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/bootstrap.min.js 200 [0.03, 127.0.0.1:39056][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/LaptopBook.png 200 [0.05, 127.0.0.1:39050][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/faq/js/jquery-2.1.1.js 200 [0.13, 127.0.0.1:39056][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/jobphone.png 200 [0.04, 127.0.0.1:39054][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homelive.png 200 [0.07, 127.0.0.1:39054][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/get3.png 304 [0.05, 127.0.0.1:39050][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/get2.png 304 [0.04, 127.0.0.1:39052][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/get1.png 304 [0.04, 127.0.0.1:39058][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/hq1.png 304 [0.05, 127.0.0.1:39060][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/testi.png 200 [0.11, 127.0.0.1:39056][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/hq2.png 304 [0.07, 127.0.0.1:39050][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/client3.png 304 [0.07, 127.0.0.1:39054][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/client2.png 304 [0.08, 127.0.0.1:39060][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/client1.png 304 [0.08, 127.0.0.1:39052][0m
[2019-04-07 22:14:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/jobban2.png 200 [0.11, 127.0.0.1:39058][0m
[2019-04-07 22:14:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.48, 127.0.0.1:39056][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/ 200 [0.21, 127.0.0.1:39056][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/aoc.png 200 [0.05, 127.0.0.1:39056][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/prooo.png 200 [0.17, 127.0.0.1:39052][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/graduate.png 200 [0.21, 127.0.0.1:39058][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/radio1.png 304 [0.02, 127.0.0.1:39050][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/womann.jpg 200 [0.07, 127.0.0.1:39054][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/wok.png 200 [0.10, 127.0.0.1:39056][0m
[2019-04-07 22:14:15] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/aboutrec.png 200 [0.12, 127.0.0.1:39060][0m
[2019-04-07 22:14:30] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/terms/ 200 [0.13, 127.0.0.1:39060][0m
[2019-04-07 22:14:56] INFO [django.channels.server.log_action:147] [32mHTTP GET /workexperience/pay/ 302 [0.01, 127.0.0.1:39060][0m
[2019-04-07 22:14:56] INFO [django.channels.server.log_action:141] [mHTTP GET /login/?next=/workexperience/pay/ 200 [0.04, 127.0.0.1:39060][0m
[2019-04-07 22:14:56] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.07, 127.0.0.1:39060][0m
[2019-04-07 22:14:56] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-07 22:14:56] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.08, 127.0.0.1:39060][0m
[2019-04-07 22:15:18] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/?next=/workexperience/pay/ 302 [1.17, 127.0.0.1:39060][0m
[2019-04-07 22:15:18] INFO [django.channels.server.log_action:147] [32mHTTP GET /workexperience/pay/ 302 [0.13, 127.0.0.1:39060][0m
[2019-04-07 22:15:18] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.31, 127.0.0.1:39060][0m
[2019-04-07 22:15:18] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/prof2.png 200 [0.02, 127.0.0.1:39060][0m
[2019-04-07 22:15:18] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/prof1.png 304 [0.01, 127.0.0.1:39140][0m
[2019-04-07 22:22:41] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.22, 127.0.0.1:39292][0m
[2019-04-07 22:23:25] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.24, 127.0.0.1:39292][0m
[2019-04-07 22:23:30] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.11, 127.0.0.1:39292][0m
[2019-04-07 22:30:34] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.79, 127.0.0.1:39424][0m
[2019-04-07 22:30:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39424][0m
[2019-04-07 22:32:08] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.23, 127.0.0.1:39448][0m
[2019-04-07 22:32:18] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39448][0m
[2019-04-07 22:34:52] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.22, 127.0.0.1:39466][0m
[2019-04-07 22:34:54] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39466][0m
[2019-04-07 22:35:14] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.31, 127.0.0.1:39466][0m
[2019-04-07 22:35:16] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39466][0m
[2019-04-07 22:37:45] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/profile/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 578, in workexprofile
    group.append(sta.id)
AttributeError: 'NoneType' object has no attribute 'append'
[2019-04-07 22:37:45] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /workexperience/profile/ 500 [0.51, 127.0.0.1:39486][0m
[2019-04-07 22:38:16] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.89, 127.0.0.1:39490][0m
[2019-04-07 22:38:18] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39490][0m
[2019-04-07 22:41:44] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.86, 127.0.0.1:39504][0m
[2019-04-07 22:41:45] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39504][0m
[2019-04-07 22:44:05] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.31, 127.0.0.1:39514][0m
[2019-04-07 22:44:14] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39514][0m
[2019-04-07 22:44:25] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.23, 127.0.0.1:39514][0m
[2019-04-07 22:44:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39514][0m
[2019-04-07 22:44:45] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.20, 127.0.0.1:39514][0m
[2019-04-07 22:44:48] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39514][0m
[2019-04-07 22:45:01] INFO [django.channels.server.log_action:147] [32mHTTP GET /admin 302 [0.85, 127.0.0.1:39514][0m
[2019-04-07 22:45:02] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/login/?next=/admin 200 [0.50, 127.0.0.1:39514][0m
[2019-04-07 22:45:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39514][0m
[2019-04-07 22:45:02] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.05, 127.0.0.1:39514][0m
[2019-04-07 22:45:02] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.04, 127.0.0.1:39526][0m
[2019-04-07 22:45:02] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.04, 127.0.0.1:39528][0m
[2019-04-07 22:45:13] INFO [django.channels.server.log_action:141] [mHTTP POST /admin/login/?next=/admin 200 [0.52, 127.0.0.1:39528][0m
[2019-04-07 22:45:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39528][0m
[2019-04-07 22:45:55] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/profile/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 576, in workexprofile
    print(status.id)
AttributeError: 'QuerySet' object has no attribute 'id'
[2019-04-07 22:45:56] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /workexperience/profile/ 500 [0.49, 127.0.0.1:39530][0m
[2019-04-07 22:46:26] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/profile/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 578, in workexprofile
    print(stat.id)
NameError: name 'stat' is not defined
[2019-04-07 22:46:26] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /workexperience/profile/ 500 [0.44, 127.0.0.1:39534][0m
[2019-04-07 22:46:41] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.80, 127.0.0.1:39536][0m
[2019-04-07 22:46:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39536][0m
[2019-04-07 22:48:44] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.92, 127.0.0.1:39562][0m
[2019-04-07 22:48:53] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39562][0m
[2019-04-07 22:49:38] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.94, 127.0.0.1:39568][0m
[2019-04-07 22:49:39] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39568][0m
[2019-04-07 22:50:11] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/login/?next=/admin 302 [0.60, 127.0.0.1:39568][0m
[2019-04-07 22:50:12] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [0.88, 127.0.0.1:39568][0m
[2019-04-07 22:50:12] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39568][0m
[2019-04-07 22:50:20] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/ 200 [0.55, 127.0.0.1:39568][0m
[2019-04-07 22:50:20] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39584][0m
[2019-04-07 22:50:20] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.11, 127.0.0.1:39568][0m
[2019-04-07 22:50:20] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.14, 127.0.0.1:39580][0m
[2019-04-07 22:50:20] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.17, 127.0.0.1:39582][0m
[2019-04-07 22:50:20] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/sorting-icons.svg 304 [0.01, 127.0.0.1:39582][0m
[2019-04-07 22:50:36] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/ 200 [0.33, 127.0.0.1:39582][0m
[2019-04-07 22:50:36] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39582][0m
[2019-04-07 22:50:40] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/ 200 [0.68, 127.0.0.1:39582][0m
[2019-04-07 22:50:40] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:39582][0m
[2019-04-07 22:50:40] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39580][0m
[2019-04-07 22:50:55] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/ 200 [0.33, 127.0.0.1:39580][0m
[2019-04-07 22:50:55] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39580][0m
[2019-04-07 22:50:59] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/ 200 [0.40, 127.0.0.1:39580][0m
[2019-04-07 22:50:59] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39580][0m
[2019-04-07 22:51:04] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/users/customuser/ 200 [1.61, 127.0.0.1:39580][0m
[2019-04-07 22:51:04] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39582][0m
[2019-04-07 22:51:04] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.10, 127.0.0.1:39580][0m
[2019-04-07 22:51:08] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/users/customuser/?q=mololuwa 200 [0.36, 127.0.0.1:39580][0m
[2019-04-07 22:51:08] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39582][0m
[2019-04-07 22:51:08] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:39580][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/users/customuser/2/change/?_changelist_filters=q%3Dmololuwa 200 [1.10, 127.0.0.1:39580][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/SelectBox.js 200 [0.17, 127.0.0.1:39582][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.10, 127.0.0.1:39596][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/SelectFilter2.js 200 [0.19, 127.0.0.1:39568][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/calendar.js 200 [0.16, 127.0.0.1:39584][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.20, 127.0.0.1:39580][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/admin/DateTimeShortcuts.js 200 [0.16, 127.0.0.1:39594][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/img/icon-unknown.svg 200 [0.05, 127.0.0.1:39580][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/img/selector-icons.svg 200 [0.06, 127.0.0.1:39596][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/img/icon-unknown-alt.svg 200 [0.05, 127.0.0.1:39594][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/icon-calendar.svg 304 [0.02, 127.0.0.1:39594][0m
[2019-04-07 22:51:11] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/icon-clock.svg 304 [0.03, 127.0.0.1:39596][0m
[2019-04-07 22:51:17] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/users/customuser/2/change/?_changelist_filters=q%3Dmololuwa 302 [0.34, 127.0.0.1:39596][0m
[2019-04-07 22:51:18] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/users/customuser/?q=mololuwa 200 [0.38, 127.0.0.1:39596][0m
[2019-04-07 22:51:18] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:39594][0m
[2019-04-07 22:51:18] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:39596][0m
[2019-04-07 22:51:20] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/logout/ 200 [0.17, 127.0.0.1:39596][0m
[2019-04-07 22:51:20] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39596][0m
[2019-04-07 22:51:22] INFO [django.channels.server.log_action:147] [32mHTTP GET /admin/ 302 [0.02, 127.0.0.1:39596][0m
[2019-04-07 22:51:22] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/login/?next=/admin/ 200 [0.09, 127.0.0.1:39596][0m
[2019-04-07 22:51:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39596][0m
[2019-04-07 22:51:29] INFO [django.channels.server.log_action:141] [mHTTP POST /admin/login/?next=/admin/ 200 [0.50, 127.0.0.1:39596][0m
[2019-04-07 22:51:29] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39596][0m
[2019-04-07 22:51:34] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/login/?next=/admin/ 302 [0.62, 127.0.0.1:39596][0m
[2019-04-07 22:51:35] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/ 200 [0.30, 127.0.0.1:39596][0m
[2019-04-07 22:51:35] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39596][0m
[2019-04-07 22:51:39] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/add/ 200 [0.64, 127.0.0.1:39596][0m
[2019-04-07 22:51:39] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:39594][0m
[2019-04-07 22:51:39] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.12, 127.0.0.1:39596][0m
[2019-04-07 22:51:41] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/ 200 [0.28, 127.0.0.1:39596][0m
[2019-04-07 22:51:46] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/add/ 200 [0.38, 127.0.0.1:39596][0m
[2019-04-07 22:51:46] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39594][0m
[2019-04-07 22:51:46] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:39596][0m
[2019-04-07 22:52:09] INFO [django.channels.server.log_action:141] [mHTTP POST /admin/home/wetask/add/ 200 [0.49, 127.0.0.1:39596][0m
[2019-04-07 22:52:09] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39594][0m
[2019-04-07 22:52:09] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.15, 127.0.0.1:39596][0m
[2019-04-07 22:52:15] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/home/wetask/add/ 302 [0.24, 127.0.0.1:39596][0m
[2019-04-07 22:52:15] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/ 200 [0.33, 127.0.0.1:39596][0m
[2019-04-07 22:52:16] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:39596][0m
[2019-04-07 22:52:16] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:39594][0m
[2019-04-07 22:52:21] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.40, 127.0.0.1:39594][0m
[2019-04-07 22:52:23] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39594][0m
[2019-04-07 22:52:36] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/ 200 [0.31, 127.0.0.1:39594][0m
[2019-04-07 22:52:37] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39594][0m
[2019-04-07 22:52:40] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/ 200 [0.44, 127.0.0.1:39594][0m
[2019-04-07 22:52:40] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:39594][0m
[2019-04-07 22:52:40] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39596][0m
[2019-04-07 22:52:51] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/1/change/ 200 [0.46, 127.0.0.1:39596][0m
[2019-04-07 22:52:51] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:39596][0m
[2019-04-07 22:52:51] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:39596][0m
[2019-04-07 22:53:14] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/1/change/ 200 [0.52, 127.0.0.1:39596][0m
[2019-04-07 22:53:14] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39594][0m
[2019-04-07 22:53:14] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:39596][0m
[2019-04-07 22:53:17] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/1/change/ 200 [0.57, 127.0.0.1:39596][0m
[2019-04-07 22:53:19] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/ 200 [0.33, 127.0.0.1:39596][0m
[2019-04-07 22:53:22] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wework/4/change/ 200 [0.43, 127.0.0.1:39596][0m
[2019-04-07 22:53:22] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:39596][0m
[2019-04-07 22:53:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39594][0m
[2019-04-07 22:53:24] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/2/change/ 200 [0.37, 127.0.0.1:39594][0m
[2019-04-07 22:53:24] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:39596][0m
[2019-04-07 22:53:24] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:39594][0m
[2019-04-07 22:53:34] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/ 200 [0.40, 127.0.0.1:39594][0m
[2019-04-07 22:53:34] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:39596][0m
[2019-04-07 22:53:34] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:39594][0m
[2019-04-07 22:55:47] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.27, 127.0.0.1:39648][0m
[2019-04-07 22:55:49] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39648][0m
[2019-04-07 22:56:06] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.30, 127.0.0.1:39648][0m
[2019-04-07 22:56:24] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.22, 127.0.0.1:39648][0m
[2019-04-07 22:56:34] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39648][0m
[2019-04-07 22:57:20] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [1.00, 127.0.0.1:39680][0m
[2019-04-07 22:57:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39680][0m
[2019-04-07 22:58:11] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [1.05, 127.0.0.1:39688][0m
[2019-04-07 22:58:12] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39688][0m
[2019-04-07 22:58:26] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.83, 127.0.0.1:39696][0m
[2019-04-07 22:58:28] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:39696][0m
[2019-04-07 22:58:51] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.80, 127.0.0.1:39700][0m
[2019-04-07 22:58:52] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39700][0m
[2019-04-07 23:00:08] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.94, 127.0.0.1:39710][0m
[2019-04-07 23:00:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39710][0m
[2019-04-08 21:31:14] INFO [django.channels.server.log_action:147] [32mHTTP GET /admin/home/wetask/ 302 [1.15, 127.0.0.1:53642][0m
[2019-04-08 21:31:14] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/login/?next=/admin/home/wetask/ 200 [0.29, 127.0.0.1:53642][0m
[2019-04-08 21:31:14] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:53642][0m
[2019-04-08 21:31:15] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-08 21:31:15] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.09, 127.0.0.1:53642][0m
[2019-04-08 21:31:31] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/login/?next=/admin/home/wetask/ 302 [0.79, 127.0.0.1:53642][0m
[2019-04-08 21:31:32] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wetask/ 200 [0.52, 127.0.0.1:53642][0m
[2019-04-08 21:31:32] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:53646][0m
[2019-04-08 21:31:32] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.18, 127.0.0.1:53642][0m
[2019-04-08 21:31:37] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.27, 127.0.0.1:53642][0m
[2019-04-08 21:31:37] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.17, 127.0.0.1:53642][0m
[2019-04-08 21:31:42] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.37, 127.0.0.1:53642][0m
[2019-04-08 21:35:00] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.31, 127.0.0.1:53736][0m
[2019-04-08 21:36:58] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.17, 127.0.0.1:53816][0m
[2019-04-08 21:42:10] INFO [django.channels.server.log_action:141] [mHTTP GET /logout 200 [0.28, 127.0.0.1:53884][0m
[2019-04-08 21:42:11] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/slide1.png 200 [0.03, 127.0.0.1:53884][0m
[2019-04-08 21:42:12] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.10, 127.0.0.1:53884][0m
[2019-04-08 21:42:15] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/ 200 [0.13, 127.0.0.1:53884][0m
[2019-04-08 21:42:20] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/terms/ 200 [0.10, 127.0.0.1:53884][0m
[2019-04-08 21:42:23] INFO [django.channels.server.log_action:147] [32mHTTP GET /workexperience/pay/ 302 [0.02, 127.0.0.1:53884][0m
[2019-04-08 21:42:23] INFO [django.channels.server.log_action:141] [mHTTP GET /login/?next=/workexperience/pay/ 200 [0.04, 127.0.0.1:53884][0m
[2019-04-08 21:42:23] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.07, 127.0.0.1:53884][0m
[2019-04-08 21:42:29] INFO [django.channels.server.log_action:141] [mHTTP GET /signup 200 [0.03, 127.0.0.1:53884][0m
[2019-04-08 21:42:39] INFO [django.channels.server.log_action:141] [mHTTP POST /signup 200 [0.07, 127.0.0.1:53884][0m
[2019-04-08 21:42:46] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.03, 127.0.0.1:53884][0m
[2019-04-08 21:42:53] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.56, 127.0.0.1:53884][0m
[2019-04-08 21:42:53] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.14, 127.0.0.1:53884][0m
[2019-04-08 21:42:54] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs//list-bg.png 200 [0.07, 127.0.0.1:53884][0m
[2019-04-08 21:43:08] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/ 200 [0.18, 127.0.0.1:53884][0m
[2019-04-08 21:43:11] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/terms/ 200 [0.12, 127.0.0.1:53884][0m
[2019-04-08 21:43:19] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/pay/ 200 [0.29, 127.0.0.1:53884][0m
[2019-04-08 21:44:20] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.15, 127.0.0.1:53960][0m
[2019-04-08 21:44:24] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/ 200 [0.15, 127.0.0.1:53960][0m
[2019-04-08 21:45:08] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/terms/ 200 [0.16, 127.0.0.1:53960][0m
[2019-04-08 21:45:12] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/pay/ 200 [0.16, 127.0.0.1:53960][0m
[2019-04-08 21:50:27] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.42, 127.0.0.1:54272][0m
[2019-04-09 21:34:59] WARNING [django.request.get_response:93] Not Found: /robots.txt
[2019-04-09 21:34:59] WARNING [django.channels.server.log_action:149] [33mHTTP GET /robots.txt 404 [0.21, 127.0.0.1:34680][0m
[2019-04-09 21:35:00] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [1.45, 127.0.0.1:34678][0m
[2019-04-09 21:35:01] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/style.css 304 [0.49, 127.0.0.1:34686][0m
[2019-04-09 21:35:01] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/logo.png 304 [0.30, 127.0.0.1:34688][0m
[2019-04-09 21:35:01] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js 304 [0.67, 127.0.0.1:34678][0m
[2019-04-09 21:35:01] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newdesigner/js/validation/jquery.validate.js 304 [0.67, 127.0.0.1:34680][0m
[2019-04-09 21:35:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newdesigner/fonts/fontsstylesheet.css 304 [0.03, 127.0.0.1:34680][0m
[2019-04-09 21:35:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/faq/js/main.js 304 [0.02, 127.0.0.1:34680][0m
[2019-04-09 21:35:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/js/waterbubble.js 304 [0.03, 127.0.0.1:34688][0m
[2019-04-09 21:35:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/faq/js/jquery.mobile.custom.min.js 304 [0.03, 127.0.0.1:34686][0m
[2019-04-09 21:35:02] INFO [django.channels.server.log_action:141] [mHTTP GET /static/faq/js/jquery-2.1.1.js 200 [0.17, 127.0.0.1:34678][0m
[2019-04-09 21:35:02] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.15, 127.0.0.1:34678][0m
[2019-04-09 21:35:07] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.04, 127.0.0.1:34678][0m
[2019-04-09 21:35:07] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/styles.css 304 [0.01, 127.0.0.1:34678][0m
[2019-04-09 21:35:08] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.15, 127.0.0.1:34678][0m
[2019-04-09 21:35:11] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-09 21:35:11] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.08, 127.0.0.1:34678][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.77, 127.0.0.1:34678][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.20, 127.0.0.1:34678][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/logout1.png 304 [0.01, 127.0.0.1:34686][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/icon1.png 304 [0.02, 127.0.0.1:34678][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/lin-logo.png 304 [0.02, 127.0.0.1:34678][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/ppt.png 304 [0.04, 127.0.0.1:34688][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/button-left.png 304 [0.05, 127.0.0.1:34686][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/rchsaa.png 304 [0.03, 127.0.0.1:34680][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/amazons.png 304 [0.03, 127.0.0.1:34720][0m
[2019-04-09 21:35:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/jjava.png 304 [0.04, 127.0.0.1:34718][0m
[2019-04-09 21:35:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/ajs.png 304 [0.04, 127.0.0.1:34678][0m
[2019-04-09 21:35:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/csecurity.png 304 [0.03, 127.0.0.1:34680][0m
[2019-04-09 21:35:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/biz.png 304 [0.02, 127.0.0.1:34718][0m
[2019-04-09 21:35:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/dba.png 304 [0.03, 127.0.0.1:34678][0m
[2019-04-09 21:35:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/py.png 304 [0.02, 127.0.0.1:34680][0m
[2019-04-09 21:35:28] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs//list-bg.png 200 [0.05, 127.0.0.1:34680][0m
[2019-04-09 21:35:46] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.38, 127.0.0.1:34680][0m
[2019-04-09 21:54:28] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.15, 127.0.0.1:34824][0m
[2019-04-09 21:54:35] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:34824][0m
[2019-04-09 22:09:45] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [1.05, 127.0.0.1:35292][0m
[2019-04-09 22:09:48] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:35292][0m
[2019-04-09 22:12:26] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.93, 127.0.0.1:35340][0m
[2019-04-09 22:12:28] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:35340][0m
[2019-04-09 22:12:52] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.77, 127.0.0.1:35370][0m
[2019-04-09 22:12:53] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:35370][0m
[2019-04-09 22:16:30] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.19, 127.0.0.1:35392][0m
[2019-04-09 22:16:31] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:35392][0m
[2019-04-09 22:18:48] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.31, 127.0.0.1:35434][0m
[2019-04-09 22:18:49] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:35434][0m
[2019-04-09 22:26:49] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.16, 127.0.0.1:35672][0m
[2019-04-10 20:59:35] INFO [django.channels.server.log_action:147] [32mHTTP GET /workexperience/apply/ 302 [0.64, 127.0.0.1:33924][0m
[2019-04-10 20:59:35] INFO [django.channels.server.log_action:141] [mHTTP GET /login/?next=/workexperience/apply/ 200 [0.11, 127.0.0.1:33924][0m
[2019-04-10 20:59:36] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.36, 127.0.0.1:33924][0m
[2019-04-10 20:59:37] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-10 20:59:37] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.11, 127.0.0.1:33924][0m
[2019-04-10 20:59:45] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/?next=/workexperience/apply/ 302 [0.72, 127.0.0.1:33924][0m
[2019-04-10 20:59:45] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.41, 127.0.0.1:33924][0m
[2019-04-10 21:15:44] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.18, 127.0.0.1:34346][0m
[2019-04-10 21:15:47] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:34346][0m
[2019-04-10 21:26:43] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.17, 127.0.0.1:34440][0m
[2019-04-10 21:26:55] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:34440][0m
[2019-04-10 21:30:30] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.19, 127.0.0.1:34512][0m
[2019-04-10 21:30:45] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.16, 127.0.0.1:34512][0m
[2019-04-10 21:31:05] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:34512][0m
[2019-04-10 21:31:14] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.21, 127.0.0.1:34512][0m
[2019-04-10 21:31:27] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.17, 127.0.0.1:34512][0m
[2019-04-10 21:31:34] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:34512][0m
[2019-04-10 21:31:52] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.18, 127.0.0.1:34512][0m
[2019-04-10 21:41:39] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.30, 127.0.0.1:34744][0m
[2019-04-10 21:41:39] WARNING [django.request.get_response:93] Not Found: /resources/demos/style.css
[2019-04-10 21:41:39] WARNING [django.channels.server.log_action:149] [33mHTTP GET /resources/demos/style.css 404 [0.16, 127.0.0.1:34744][0m
[2019-04-10 21:41:40] WARNING [django.request.get_response:93] Not Found: /resources/demos/style.css
[2019-04-10 21:41:40] WARNING [django.channels.server.log_action:149] [33mHTTP GET /resources/demos/style.css 404 [0.15, 127.0.0.1:34744][0m
[2019-04-10 21:43:12] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.91, 127.0.0.1:34780][0m
[2019-04-10 21:43:12] WARNING [django.request.get_response:93] Not Found: /resources/demos/style.css
[2019-04-10 21:43:12] WARNING [django.channels.server.log_action:149] [33mHTTP GET /resources/demos/style.css 404 [0.16, 127.0.0.1:34780][0m
[2019-04-10 21:43:14] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:34780][0m
[2019-04-10 21:43:42] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.76, 127.0.0.1:34788][0m
[2019-04-10 21:43:42] WARNING [django.request.get_response:93] Not Found: /resources/demos/style.css
[2019-04-10 21:43:42] WARNING [django.channels.server.log_action:149] [33mHTTP GET /resources/demos/style.css 404 [0.18, 127.0.0.1:34788][0m
[2019-04-10 21:43:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:34788][0m
[2019-04-10 22:20:55] INFO [django.channels.server.log_action:147] [32mHTTP GET /workexperience/apply/ 302 [0.07, 127.0.0.1:35152][0m
[2019-04-10 22:20:55] INFO [django.channels.server.log_action:141] [mHTTP GET /login/?next=/workexperience/apply/ 200 [0.07, 127.0.0.1:35152][0m
[2019-04-10 22:21:08] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/?next=/workexperience/apply/ 302 [1.57, 127.0.0.1:35152][0m
[2019-04-10 22:21:09] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.30, 127.0.0.1:35152][0m
[2019-04-10 22:21:09] WARNING [django.request.get_response:93] Not Found: /resources/demos/style.css
[2019-04-10 22:21:09] WARNING [django.channels.server.log_action:149] [33mHTTP GET /resources/demos/style.css 404 [0.47, 127.0.0.1:35152][0m
[2019-04-10 22:22:11] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.19, 127.0.0.1:35174][0m
[2019-04-10 22:22:13] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.09, 127.0.0.1:35174][0m
[2019-04-10 22:26:19] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.41, 127.0.0.1:35232][0m
[2019-04-10 22:26:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:35232][0m
[2019-04-10 22:26:33] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.25, 127.0.0.1:35232][0m
[2019-04-10 22:43:25] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.33, 127.0.0.1:35508][0m
[2019-04-10 22:43:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 200 [0.02, 127.0.0.1:35508][0m
[2019-04-10 22:43:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.js 200 [0.06, 127.0.0.1:35510][0m
[2019-04-10 22:43:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 200 [0.07, 127.0.0.1:35512][0m
[2019-04-10 22:44:06] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.25, 127.0.0.1:35510][0m
[2019-04-10 22:47:43] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.19, 127.0.0.1:36324][0m
[2019-04-10 22:49:02] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.26, 127.0.0.1:36980][0m
[2019-04-10 22:49:03] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:36980][0m
[2019-04-10 22:50:20] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.26, 127.0.0.1:37610][0m
[2019-04-10 22:50:21] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 304 [0.01, 127.0.0.1:37612][0m
[2019-04-10 22:50:21] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.05, 127.0.0.1:37610][0m
[2019-04-10 22:50:21] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:37610][0m
[2019-04-10 22:54:04] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.25, 127.0.0.1:39488][0m
[2019-04-10 22:54:05] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39488][0m
[2019-04-10 22:54:22] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.20, 127.0.0.1:39488][0m
[2019-04-10 22:54:51] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.23, 127.0.0.1:39488][0m
[2019-04-10 22:55:33] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.27, 127.0.0.1:39488][0m
[2019-04-10 22:55:33] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39488][0m
[2019-04-10 22:55:40] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.21, 127.0.0.1:39488][0m
[2019-04-10 22:55:41] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:39488][0m
[2019-04-10 22:56:05] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.28, 127.0.0.1:39488][0m
[2019-04-10 22:56:06] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:39488][0m
[2019-04-10 22:59:20] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.23, 127.0.0.1:42070][0m
[2019-04-10 22:59:21] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 200 [0.03, 127.0.0.1:42070][0m
[2019-04-10 22:59:21] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 200 [0.04, 127.0.0.1:42080][0m
[2019-04-10 22:59:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:42080][0m
[2019-04-10 22:59:42] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.14, 127.0.0.1:42080][0m
[2019-04-10 22:59:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.04, 127.0.0.1:42080][0m
[2019-04-10 22:59:55] INFO [django.channels.server.log_action:141] [mHTTP GET /faq 200 [0.72, 127.0.0.1:42080][0m
[2019-04-10 23:00:06] INFO [django.channels.server.log_action:141] [mHTTP GET /faq 200 [0.16, 127.0.0.1:42080][0m
[2019-04-10 23:00:07] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:42080][0m
[2019-04-10 23:00:25] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.29, 127.0.0.1:42080][0m
[2019-04-10 23:00:29] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.23, 127.0.0.1:42080][0m
[2019-04-10 23:00:31] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.24, 127.0.0.1:42080][0m
[2019-04-10 23:00:31] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:42080][0m
[2019-04-11 10:44:24] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [1.29, 127.0.0.1:37446][0m
[2019-04-11 10:44:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/css/main.css 304 [0.02, 127.0.0.1:37446][0m
[2019-04-11 10:44:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/css/newstyle2.css 304 [0.02, 127.0.0.1:37446][0m
[2019-04-11 10:44:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.01, 127.0.0.1:37446][0m
[2019-04-11 10:44:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 304 [0.01, 127.0.0.1:37450][0m
[2019-04-11 10:44:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/LaptopBook.png 200 [0.08, 127.0.0.1:37450][0m
[2019-04-11 10:44:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.16, 127.0.0.1:37450][0m
[2019-04-11 10:44:34] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.05, 127.0.0.1:37450][0m
[2019-04-11 10:44:34] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.07, 127.0.0.1:37450][0m
[2019-04-11 10:44:35] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-11 10:44:35] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.19, 127.0.0.1:37450][0m
[2019-04-11 10:44:43] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.95, 127.0.0.1:37450][0m
[2019-04-11 10:44:44] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.23, 127.0.0.1:37450][0m
[2019-04-11 10:44:44] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs//list-bg.png 200 [0.04, 127.0.0.1:37450][0m
[2019-04-11 10:44:53] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.43, 127.0.0.1:37450][0m
[2019-04-11 10:47:09] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.23, 127.0.0.1:37590][0m
[2019-04-11 10:54:18] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.39, 127.0.0.1:41162][0m
[2019-04-11 10:54:28] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.26, 127.0.0.1:41162][0m
[2019-04-11 10:54:51] INFO [django.channels.server.log_action:141] [mHTTP GET /faq 200 [0.39, 127.0.0.1:41162][0m
[2019-04-11 10:56:42] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.38, 127.0.0.1:42198][0m
[2019-04-11 10:56:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.10, 127.0.0.1:42198][0m
[2019-04-11 10:56:58] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.32, 127.0.0.1:42198][0m
[2019-04-11 10:56:59] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:42198][0m
[2019-04-11 11:00:23] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.27, 127.0.0.1:44028][0m
[2019-04-11 11:00:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:44028][0m
[2019-04-11 11:00:37] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.28, 127.0.0.1:44028][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js 200 [0.11, 127.0.0.1:44028][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/validation/jquery.validate.js 200 [0.14, 127.0.0.1:44148][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/css/bootstrap.min.css 200 [0.16, 127.0.0.1:44150][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/style.css 200 [0.17, 127.0.0.1:44152][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/newstyle2.css 200 [0.16, 127.0.0.1:44156][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/css/style.css 200 [0.18, 127.0.0.1:44154][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/main.css 200 [0.14, 127.0.0.1:44028][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/newstylenew.css 200 [0.13, 127.0.0.1:44148][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/Projects/custom/css/projects.css 200 [0.11, 127.0.0.1:44150][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 200 [0.12, 127.0.0.1:44152][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/logo.png 200 [0.11, 127.0.0.1:44154][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/icon1.png 200 [0.11, 127.0.0.1:44156][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/bootstrap.min.js 200 [0.09, 127.0.0.1:44154][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/fonts/fontsstylesheet.css 200 [0.06, 127.0.0.1:44156][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/logout1.png 200 [0.04, 127.0.0.1:44148][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/faq/js/main.js 200 [0.07, 127.0.0.1:44152][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/faq/js/jquery.mobile.custom.min.js 200 [0.08, 127.0.0.1:44154][0m
[2019-04-11 11:00:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/js/waterbubble.js 200 [0.07, 127.0.0.1:44150][0m
[2019-04-11 11:00:39] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/jobban2.png 200 [0.04, 127.0.0.1:44150][0m
[2019-04-11 11:00:41] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:44150][0m
[2019-04-11 11:00:57] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.20, 127.0.0.1:44150][0m
[2019-04-11 11:00:58] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:44150][0m
[2019-04-11 11:02:35] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.24, 127.0.0.1:44974][0m
[2019-04-11 11:02:35] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-11 11:02:35] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.19, 127.0.0.1:44974][0m
[2019-04-11 11:06:02] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.19, 127.0.0.1:46110][0m
[2019-04-11 11:06:07] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.21, 127.0.0.1:46110][0m
[2019-04-11 11:06:19] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.20, 127.0.0.1:46110][0m
[2019-04-11 11:06:20] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:46110][0m
[2019-04-11 11:06:32] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.29, 127.0.0.1:46110][0m
[2019-04-11 11:06:33] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:46110][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.25, 127.0.0.1:46172][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js 200 [0.06, 127.0.0.1:46172][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/css/bootstrap.min.css 200 [0.07, 127.0.0.1:46176][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/newstyle2.css 200 [0.09, 127.0.0.1:46182][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/css/style.css 200 [0.10, 127.0.0.1:46180][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/style.css 200 [0.12, 127.0.0.1:46178][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/validation/jquery.validate.js 200 [0.14, 127.0.0.1:46174][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/main.css 200 [0.10, 127.0.0.1:46172][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/newstylenew.css 200 [0.08, 127.0.0.1:46176][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 200 [0.08, 127.0.0.1:46174][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 200 [0.07, 127.0.0.1:46178][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/Projects/custom/css/projects.css 200 [0.10, 127.0.0.1:46180][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/icon1.png 200 [0.06, 127.0.0.1:46172][0m
[2019-04-11 11:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/logo.png 200 [0.09, 127.0.0.1:46182][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/faq/js/jquery.mobile.custom.min.js 200 [0.04, 127.0.0.1:46182][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/js/bootstrap.min.js 200 [0.07, 127.0.0.1:46172][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/faq/js/main.js 200 [0.02, 127.0.0.1:46182][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/js/waterbubble.js 200 [0.07, 127.0.0.1:46172][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/logout1.png 200 [0.06, 127.0.0.1:46182][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/fonts/fontsstylesheet.css 200 [0.04, 127.0.0.1:46172][0m
[2019-04-11 11:07:43] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/jobban2.png 200 [0.03, 127.0.0.1:46172][0m
[2019-04-11 11:07:44] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:46172][0m
[2019-04-11 11:10:23] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.26, 127.0.0.1:46252][0m
[2019-04-11 11:10:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:46252][0m
[2019-04-11 11:11:26] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.23, 127.0.0.1:46702][0m
[2019-04-11 11:11:27] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:46702][0m
[2019-04-11 11:11:33] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.20, 127.0.0.1:46702][0m
[2019-04-11 11:11:34] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:46702][0m
[2019-04-11 11:11:45] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-11 11:11:45] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.16, 127.0.0.1:46702][0m
[2019-04-11 11:13:05] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.24, 127.0.0.1:46858][0m
[2019-04-11 11:13:22] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.19, 127.0.0.1:46858][0m
[2019-04-11 11:13:23] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:46858][0m
[2019-04-11 11:14:56] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.16, 127.0.0.1:47574][0m
[2019-04-11 11:14:57] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:47574][0m
[2019-04-11 11:15:57] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.22, 127.0.0.1:47720][0m
[2019-04-11 11:15:59] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:47720][0m
[2019-04-11 11:16:00] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/images/ui-icons_444444_256x240.png 200 [0.03, 127.0.0.1:47720][0m
[2019-04-11 11:16:13] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/images/ui-icons_555555_256x240.png 200 [0.03, 127.0.0.1:47720][0m
[2019-04-11 11:17:03] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.27, 127.0.0.1:47720][0m
[2019-04-11 11:17:04] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:47720][0m
[2019-04-11 11:25:27] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.20, 127.0.0.1:47856][0m
[2019-04-11 11:25:32] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:47856][0m
[2019-04-11 11:26:47] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [1.13, 127.0.0.1:47886][0m
[2019-04-11 11:26:48] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:47886][0m
[2019-04-11 11:27:21] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [1.23, 127.0.0.1:47898][0m
[2019-04-11 11:27:23] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:47898][0m
[2019-04-11 11:34:16] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [1.11, 127.0.0.1:47996][0m
[2019-04-11 11:34:18] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:47996][0m
[2019-04-11 11:34:54] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 542, in workexpform
    if date < datetime.datetime.now():
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
[2019-04-11 11:34:54] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.75, 127.0.0.1:47996][0m
[2019-04-11 11:35:35] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 542, in workexpform
    if date < datetime.datetime.now():
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
[2019-04-11 11:35:35] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.37, 127.0.0.1:48012][0m
[2019-04-11 11:38:43] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    date = date.strftime("%Y-%m-%d")
AttributeError: 'str' object has no attribute 'strftime'
[2019-04-11 11:38:43] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.40, 127.0.0.1:48084][0m
[2019-04-11 11:39:29] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 544, in workexpform
    date = datetime.strptime( date, "%Y-%m-%d")
AttributeError: module 'datetime' has no attribute 'strptime'
[2019-04-11 11:39:29] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.43, 127.0.0.1:48094][0m
[2019-04-11 11:40:19] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 546, in workexpform
    today = datetime.now().strftime("%Y-%m-%d")
AttributeError: module 'datetime' has no attribute 'now'
[2019-04-11 11:40:20] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.44, 127.0.0.1:48100][0m
[2019-04-11 11:41:51] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 547, in workexpform
    today = datetime.strptime( today, "%Y-%m-%d")
AttributeError: module 'datetime' has no attribute 'strptime'
[2019-04-11 11:41:52] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.48, 127.0.0.1:48102][0m
[2019-04-11 11:42:25] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 548, in workexpform
    if date < today:
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
[2019-04-11 11:42:25] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.46, 127.0.0.1:48104][0m
[2019-04-11 11:42:47] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view home.views.workexpform didn't return an HttpResponse object. It returned None instead.
[2019-04-11 11:42:47] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.33, 127.0.0.1:48106][0m
[2019-04-11 12:14:59] INFO [django.channels.server.log_action:147] [32mHTTP GET /workexperience/apply/ 302 [0.68, 127.0.0.1:48420][0m
[2019-04-11 12:14:59] INFO [django.channels.server.log_action:141] [mHTTP GET /login/?next=/workexperience/apply/ 200 [0.46, 127.0.0.1:48420][0m
[2019-04-11 12:15:09] INFO [django.channels.server.log_action:141] [mHTTP POST /login/?next=/workexperience/apply/ 200 [0.53, 127.0.0.1:48420][0m
[2019-04-11 12:15:16] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [1.44, 127.0.0.1:48420][0m
[2019-04-11 12:15:17] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.35, 127.0.0.1:48420][0m
[2019-04-11 12:15:33] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.37, 127.0.0.1:48420][0m
[2019-04-11 12:15:50] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = today + datetime.date.today() + datetime.timedelta(6*365/12)
TypeError: must be str, not datetime.date
[2019-04-11 12:15:50] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.62, 127.0.0.1:48420][0m
[2019-04-11 12:16:19] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = today + datetime.timedelta(6*365/12)
TypeError: must be str, not datetime.timedelta
[2019-04-11 12:16:19] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.47, 127.0.0.1:48456][0m
[2019-04-11 12:17:17] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = today + datetime.timedelta(6*365/12).strftime("%Y-%m-%d")
AttributeError: 'datetime.timedelta' object has no attribute 'strftime'
[2019-04-11 12:17:17] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.44, 127.0.0.1:48462][0m
[2019-04-11 12:19:22] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = today + datetime.datetime.today().strftime("%Y-%m-%d").timedelta(6*365/12)
AttributeError: 'str' object has no attribute 'timedelta'
[2019-04-11 12:19:23] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.44, 127.0.0.1:48536][0m
[2019-04-11 12:19:59] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = today + datetime.datetime.today().timedelta(6*365/12)
AttributeError: 'datetime.datetime' object has no attribute 'timedelta'
[2019-04-11 12:19:59] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.41, 127.0.0.1:48546][0m
[2019-04-11 12:21:16] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = today + datetime.timedelta(6*365/12)
TypeError: must be str, not datetime.timedelta
[2019-04-11 12:21:16] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.36, 127.0.0.1:48548][0m
[2019-04-11 12:22:14] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.92, 127.0.0.1:48558][0m
[2019-04-11 12:22:31] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = datetime.datetime.now().timedelta(6*365/12)
AttributeError: 'datetime.datetime' object has no attribute 'timedelta'
[2019-04-11 12:22:31] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.52, 127.0.0.1:48558][0m
[2019-04-11 12:24:50] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view home.views.workexpform didn't return an HttpResponse object. It returned None instead.
[2019-04-11 12:24:50] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.44, 127.0.0.1:48600][0m
[2019-04-11 12:25:18] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = datetime.datetime.now() + timedelta(months=6)
TypeError: 'months' is an invalid keyword argument for this function
[2019-04-11 12:25:18] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.42, 127.0.0.1:48602][0m
[2019-04-11 12:25:53] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 543, in workexpform
    month6 = datetime.datetime.now() + timedelta(month=6)
TypeError: 'month' is an invalid keyword argument for this function
[2019-04-11 12:25:53] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.44, 127.0.0.1:48604][0m
[2019-04-11 12:26:08] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.90, 127.0.0.1:48608][0m
[2019-04-11 12:26:25] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view home.views.workexpform didn't return an HttpResponse object. It returned None instead.
[2019-04-11 12:26:25] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.45, 127.0.0.1:48608][0m
[2019-04-11 12:30:37] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.86, 127.0.0.1:48630][0m
[2019-04-11 12:30:37] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.03, 127.0.0.1:48630][0m
[2019-04-11 12:30:37] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 304 [0.04, 127.0.0.1:48632][0m
[2019-04-11 12:31:01] INFO [django.channels.server.log_action:147] [32mHTTP POST /workexperience/apply/ 302 [0.54, 127.0.0.1:48632][0m
[2019-04-11 12:31:02] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.49, 127.0.0.1:48632][0m
[2019-04-11 12:34:05] INFO [django.channels.server.log_action:147] [32mHTTP GET /admin 302 [0.48, 127.0.0.1:48700][0m
[2019-04-11 12:34:06] INFO [django.channels.server.log_action:147] [32mHTTP GET /admin 302 [0.71, 127.0.0.1:48702][0m
[2019-04-11 12:34:06] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/login/?next=/admin 200 [1.31, 127.0.0.1:48700][0m
[2019-04-11 12:34:06] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/base.css 304 [0.03, 127.0.0.1:48700][0m
[2019-04-11 12:34:06] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/login.css 304 [0.03, 127.0.0.1:48704][0m
[2019-04-11 12:34:06] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/login/?next=/admin 200 [0.23, 127.0.0.1:48702][0m
[2019-04-11 12:34:06] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/responsive.css 304 [0.01, 127.0.0.1:48702][0m
[2019-04-11 12:34:07] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:48702][0m
[2019-04-11 12:34:07] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.05, 127.0.0.1:48702][0m
[2019-04-11 12:34:07] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.04, 127.0.0.1:48704][0m
[2019-04-11 12:34:07] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.06, 127.0.0.1:48700][0m
[2019-04-11 12:34:12] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/login/?next=/admin 302 [0.76, 127.0.0.1:48700][0m
[2019-04-11 12:34:13] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [0.62, 127.0.0.1:48700][0m
[2019-04-11 12:34:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/dashboard.css 304 [0.01, 127.0.0.1:48700][0m
[2019-04-11 12:34:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:48700][0m
[2019-04-11 12:34:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/icon-addlink.svg 304 [0.01, 127.0.0.1:48700][0m
[2019-04-11 12:34:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/icon-changelink.svg 304 [0.01, 127.0.0.1:48704][0m
[2019-04-11 12:34:26] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/ 200 [0.68, 127.0.0.1:48704][0m
[2019-04-11 12:34:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/changelists.css 304 [0.05, 127.0.0.1:48702][0m
[2019-04-11 12:34:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/prepopulate.js 304 [0.04, 127.0.0.1:48708][0m
[2019-04-11 12:34:26] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/core.js 304 [0.04, 127.0.0.1:48710][0m
[2019-04-11 12:34:26] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.14, 127.0.0.1:48704][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.10, 127.0.0.1:48702][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.20, 127.0.0.1:48700][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.08, 127.0.0.1:48708][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/actions.js 304 [0.08, 127.0.0.1:48710][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/jquery.init.js 304 [0.07, 127.0.0.1:48704][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.21, 127.0.0.1:48706][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/urlify.js 304 [0.05, 127.0.0.1:48702][0m
[2019-04-11 12:34:27] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/tooltag-add.svg 304 [0.01, 127.0.0.1:48706][0m
[2019-04-11 12:34:30] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/7/change/ 200 [1.13, 127.0.0.1:48706][0m
[2019-04-11 12:34:30] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/forms.css 304 [0.01, 127.0.0.1:48702][0m
[2019-04-11 12:34:30] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/change_form.js 304 [0.04, 127.0.0.1:48704][0m
[2019-04-11 12:34:30] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/js/prepopulate_init.js 304 [0.04, 127.0.0.1:48710][0m
[2019-04-11 12:34:30] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:48708][0m
[2019-04-11 12:34:31] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/widgets.css 304 [0.01, 127.0.0.1:48710][0m
[2019-04-11 12:34:31] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.16, 127.0.0.1:48706][0m
[2019-04-11 12:38:02] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.74, 127.0.0.1:48822][0m
[2019-04-11 12:38:05] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/images/ui-icons_444444_256x240.png 304 [0.01, 127.0.0.1:48822][0m
[2019-04-11 12:38:28] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.29, 127.0.0.1:48822][0m
[2019-04-11 12:38:29] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:48822][0m
[2019-04-11 12:56:42] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [1.58, 127.0.0.1:48962][0m
[2019-04-11 12:56:43] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [0.32, 127.0.0.1:48964][0m
[2019-04-11 12:56:43] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:48964][0m
[2019-04-11 12:56:48] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/ 200 [0.46, 127.0.0.1:48964][0m
[2019-04-11 12:56:48] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:48962][0m
[2019-04-11 12:56:48] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.22, 127.0.0.1:48964][0m
[2019-04-11 12:56:53] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/7/change/ 200 [1.17, 127.0.0.1:48964][0m
[2019-04-11 12:56:53] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:48962][0m
[2019-04-11 12:56:53] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.12, 127.0.0.1:48964][0m
[2019-04-11 13:00:55] INFO [django.channels.server.log_action:147] [32mHTTP GET /admin/home/ 302 [0.96, 127.0.0.1:48978][0m
[2019-04-11 13:00:55] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/login/?next=/admin/home/ 200 [0.17, 127.0.0.1:48978][0m
[2019-04-11 13:00:56] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:48978][0m
[2019-04-11 13:01:17] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/login/?next=/admin/home/ 302 [0.63, 127.0.0.1:48978][0m
[2019-04-11 13:01:17] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /admin/home/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'home_wepeoples.person_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/usr/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/django/template/context.py", line 250, in bind_template
    updates.update(processor(self.request))
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/context_processors.py", line 19, in workexperience
    workexp = wepeoples.objects.get(user=request.user)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'home_wepeoples.person_id' in 'field list'")
[2019-04-11 13:01:18] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /admin/home/ 500 [1.26, 127.0.0.1:48978][0m
[2019-04-11 13:01:26] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /admin/home/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'home_wepeoples.person_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/usr/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/django/template/context.py", line 250, in bind_template
    updates.update(processor(self.request))
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/context_processors.py", line 19, in workexperience
    workexp = wepeoples.objects.get(user=request.user)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'home_wepeoples.person_id' in 'field list'")
[2019-04-11 13:01:27] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /admin/home/ 500 [0.77, 127.0.0.1:48978][0m
[2019-04-11 13:03:38] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/ 200 [1.64, 127.0.0.1:48998][0m
[2019-04-11 13:03:39] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:48998][0m
[2019-04-11 13:03:42] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/ 200 [0.39, 127.0.0.1:48998][0m
[2019-04-11 13:03:42] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:49004][0m
[2019-04-11 13:03:42] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:48998][0m
[2019-04-11 13:03:45] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/3/change/ 200 [0.76, 127.0.0.1:48998][0m
[2019-04-11 13:03:45] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.10, 127.0.0.1:48998][0m
[2019-04-11 13:03:45] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:49004][0m
[2019-04-11 13:04:54] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/ 200 [1.41, 127.0.0.1:49006][0m
[2019-04-11 13:04:54] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:04:57] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/ 200 [0.25, 127.0.0.1:49006][0m
[2019-04-11 13:04:57] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:49008][0m
[2019-04-11 13:04:57] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.10, 127.0.0.1:49006][0m
[2019-04-11 13:04:59] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/add/ 200 [0.24, 127.0.0.1:49006][0m
[2019-04-11 13:04:59] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49008][0m
[2019-04-11 13:04:59] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:49006][0m
[2019-04-11 13:05:13] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/home/werole/add/ 302 [0.16, 127.0.0.1:49006][0m
[2019-04-11 13:05:13] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/ 200 [0.31, 127.0.0.1:49006][0m
[2019-04-11 13:05:13] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:49006][0m
[2019-04-11 13:05:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:05:13] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/icon-yes.svg 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:05:15] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/add/ 200 [0.29, 127.0.0.1:49006][0m
[2019-04-11 13:05:15] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:49006][0m
[2019-04-11 13:05:15] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.05, 127.0.0.1:49006][0m
[2019-04-11 13:05:48] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/home/werole/add/ 302 [0.29, 127.0.0.1:49006][0m
[2019-04-11 13:05:48] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/ 200 [0.29, 127.0.0.1:49006][0m
[2019-04-11 13:05:49] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:49006][0m
[2019-04-11 13:05:49] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:05:50] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/add/ 200 [0.22, 127.0.0.1:49006][0m
[2019-04-11 13:05:51] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:49006][0m
[2019-04-11 13:05:51] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:05:54] INFO [django.channels.server.log_action:147] [32mHTTP POST /admin/home/werole/add/ 302 [0.13, 127.0.0.1:49006][0m
[2019-04-11 13:05:55] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/werole/ 200 [0.45, 127.0.0.1:49006][0m
[2019-04-11 13:05:55] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49008][0m
[2019-04-11 13:05:55] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:49006][0m
[2019-04-11 13:05:57] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/ 200 [0.22, 127.0.0.1:49006][0m
[2019-04-11 13:05:57] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:05:59] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/ 200 [0.31, 127.0.0.1:49006][0m
[2019-04-11 13:05:59] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:49008][0m
[2019-04-11 13:05:59] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:49006][0m
[2019-04-11 13:06:01] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/3/change/ 200 [0.74, 127.0.0.1:49006][0m
[2019-04-11 13:06:02] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:49006][0m
[2019-04-11 13:06:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:49008][0m
[2019-04-11 13:06:10] INFO [django.channels.server.log_action:141] [mHTTP POST /admin/home/wepeoples/3/change/ 200 [0.81, 127.0.0.1:49008][0m
[2019-04-11 13:06:10] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49006][0m
[2019-04-11 13:06:11] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:49008][0m
[2019-04-11 13:06:19] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.24, 127.0.0.1:49008][0m
[2019-04-11 13:06:23] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.31, 127.0.0.1:49008][0m
[2019-04-11 13:06:44] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [0.31, 127.0.0.1:49008][0m
[2019-04-11 13:06:46] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [0.35, 127.0.0.1:49008][0m
[2019-04-11 13:06:46] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49008][0m
[2019-04-11 13:06:50] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/ 200 [0.28, 127.0.0.1:49008][0m
[2019-04-11 13:06:50] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:49008][0m
[2019-04-11 13:06:50] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:49008][0m
[2019-04-11 13:06:52] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/home/wepeoples/5/change/ 200 [0.74, 127.0.0.1:49008][0m
[2019-04-11 13:06:52] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:49008][0m
[2019-04-11 13:06:52] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:49006][0m
[2019-04-11 13:07:40] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [0.38, 127.0.0.1:49008][0m
[2019-04-11 13:07:42] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.23, 127.0.0.1:49008][0m
[2019-04-11 13:07:46] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.26, 127.0.0.1:49008][0m
[2019-04-11 13:07:47] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:49008][0m
[2019-04-11 13:11:58] INFO [django.channels.server.log_action:141] [mHTTP GET /logout 200 [0.75, 127.0.0.1:49070][0m
[2019-04-11 13:11:59] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/slide1.png 200 [0.04, 127.0.0.1:49070][0m
[2019-04-11 13:12:00] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.18, 127.0.0.1:49070][0m
[2019-04-11 13:12:03] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.03, 127.0.0.1:49070][0m
[2019-04-11 13:12:09] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.68, 127.0.0.1:49070][0m
[2019-04-11 13:12:09] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.22, 127.0.0.1:49070][0m
[2019-04-11 13:12:13] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/apply/ 200 [0.24, 127.0.0.1:49070][0m
[2019-04-11 13:12:26] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 538, in workexpform
    person = request.POST['type']
  File "/usr/lib/python3.6/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'type'
[2019-04-11 13:12:27] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.33, 127.0.0.1:49070][0m
[2019-04-11 13:12:51] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/apply/
Traceback (most recent call last):
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 553, in workexpform
    weps = wepeoples.objects.get(user=request.user)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
home.models.DoesNotExist: wepeoples matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 569, in workexpform
    relocation=relocate,last_verification=None,Paystub=None,graduation_date=None,start_date=None)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 415, in create
    obj = self.model(**kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 495, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'person_type' is an invalid keyword argument for this function
[2019-04-11 13:12:51] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/apply/ 500 [0.53, 127.0.0.1:49092][0m
[2019-04-11 13:13:34] INFO [django.channels.server.log_action:147] [32mHTTP POST /workexperience/apply/ 302 [0.83, 127.0.0.1:49094][0m
[2019-04-11 13:13:35] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.26, 127.0.0.1:49094][0m
[2019-04-11 13:14:50] INFO [django.channels.server.log_action:141] [mHTTP GET /logout 200 [0.21, 127.0.0.1:49100][0m
[2019-04-11 13:14:51] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.10, 127.0.0.1:49100][0m
[2019-04-11 13:14:52] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.03, 127.0.0.1:49100][0m
[2019-04-11 13:14:58] INFO [django.channels.server.log_action:141] [mHTTP POST /login/ 200 [0.38, 127.0.0.1:49100][0m
[2019-04-11 13:15:03] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.49, 127.0.0.1:49100][0m
[2019-04-11 13:15:03] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.15, 127.0.0.1:49100][0m
[2019-04-11 13:15:09] INFO [django.channels.server.log_action:147] [32mHTTP GET /user/account/settings 302 [0.07, 127.0.0.1:49100][0m
[2019-04-11 13:15:33] INFO [django.channels.server.log_action:141] [mHTTP GET /user/account/ec2dashboard/ 200 [23.63, 127.0.0.1:49100][0m
[2019-04-11 13:15:52] INFO [django.channels.server.log_action:141] [mHTTP GET /logout 200 [0.20, 127.0.0.1:49100][0m
[2019-04-11 13:15:53] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.12, 127.0.0.1:49100][0m
[2019-04-11 13:15:55] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.03, 127.0.0.1:49100][0m
[2019-04-11 13:16:09] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.50, 127.0.0.1:49100][0m
[2019-04-11 13:16:09] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.15, 127.0.0.1:49100][0m
[2019-04-11 13:16:13] INFO [django.channels.server.log_action:147] [32mHTTP GET /user/account/settings 302 [0.06, 127.0.0.1:49100][0m
[2019-04-11 13:16:17] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/description/Java 200 [0.28, 127.0.0.1:49152][0m
[2019-04-11 13:16:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/img/intro.jpg 200 [0.03, 127.0.0.1:49152][0m
[2019-04-11 13:16:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/img/trialimg.jpg 200 [0.03, 127.0.0.1:49154][0m
[2019-04-11 13:16:22] INFO [django.channels.server.log_action:147] [32mHTTP GET /user/account/settings 302 [0.06, 127.0.0.1:49154][0m
[2019-04-11 13:16:41] INFO [django.channels.server.log_action:141] [mHTTP GET /user/account/ec2dashboard/ 200 [19.34, 127.0.0.1:49154][0m
[2019-04-11 13:22:05] INFO [django.channels.server.log_action:141] [mHTTP GET /user/account/ec2dashboard/ 200 [20.49, 127.0.0.1:49312][0m
[2019-04-11 13:22:06] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.01, 127.0.0.1:49312][0m
[2019-04-11 13:22:18] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [3.30, 127.0.0.1:49312][0m
[2019-04-11 13:22:18] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/Movie-icon.jpg 200 [0.04, 127.0.0.1:49312][0m
[2019-04-11 13:22:18] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/images/icon9.png 304 [0.01, 127.0.0.1:49348][0m
[2019-04-11 13:22:19] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newdesigner/fonts/glyphicons-halflings-regular.woff 200 [0.03, 127.0.0.1:49312][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /jobplacements/ 200 [0.16, 127.0.0.1:49376][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/%240pay.png 200 [0.06, 127.0.0.1:49376][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/br2.png 200 [0.04, 127.0.0.1:49378][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/ent.png 200 [0.04, 127.0.0.1:49378][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/seno.png 200 [0.04, 127.0.0.1:49376][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/jobhead.png 200 [0.04, 127.0.0.1:49376][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs//init.jpg 200 [0.04, 127.0.0.1:49378][0m
[2019-04-11 13:26:17] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/race.png 200 [0.05, 127.0.0.1:49382][0m
[2019-04-11 13:28:25] INFO [django.channels.server.log_action:141] [mHTTP GET /jobplacements/apply/snr/ 200 [0.22, 127.0.0.1:49404][0m
[2019-04-11 13:28:25] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/proj-list.png 200 [0.03, 127.0.0.1:49404][0m
[2019-04-11 13:28:27] INFO [django.channels.server.log_action:141] [mHTTP GET /jobplacements/ 200 [0.13, 127.0.0.1:49404][0m
[2019-04-13 22:04:20] WARNING [django.request.get_response:93] Not Found: /robots.txt
[2019-04-13 22:04:20] WARNING [django.channels.server.log_action:149] [33mHTTP GET /robots.txt 404 [0.15, 127.0.0.1:43942][0m
[2019-04-13 22:04:21] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [1.06, 127.0.0.1:43940][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/css/newstyle2.css 200 [0.13, 127.0.0.1:43940][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.01, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 200 [0.19, 127.0.0.1:43942][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/LaptopBook.png 200 [0.07, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/jobphone.png 304 [0.01, 127.0.0.1:43942][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homelive.png 200 [0.04, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/get3.png 304 [0.01, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/get2.png 304 [0.01, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/get1.png 304 [0.01, 127.0.0.1:43942][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/testi.png 200 [0.04, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/hq1.png 304 [0.01, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/hq2.png 304 [0.06, 127.0.0.1:43950][0m
[2019-04-13 22:04:22] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/client3.png 304 [0.06, 127.0.0.1:43942][0m
[2019-04-13 22:04:23] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/client1.png 304 [0.07, 127.0.0.1:43940][0m
[2019-04-13 22:04:23] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/client2.png 304 [0.07, 127.0.0.1:43962][0m
[2019-04-13 22:04:23] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/jobban2.png 200 [0.07, 127.0.0.1:43964][0m
[2019-04-13 22:04:23] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.17, 127.0.0.1:43966][0m
[2019-04-13 22:04:32] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.05, 127.0.0.1:43966][0m
[2019-04-13 22:04:33] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.11, 127.0.0.1:43966][0m
[2019-04-13 22:04:35] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-13 22:04:35] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.09, 127.0.0.1:43966][0m
[2019-04-13 22:04:42] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.95, 127.0.0.1:43966][0m
[2019-04-13 22:04:42] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.17, 127.0.0.1:43966][0m
[2019-04-13 22:05:05] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [15.14, 127.0.0.1:43966][0m
[2019-04-13 22:30:35] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topics/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 61, in get_context_data
    context['totalstats'] = totalstat(self.request.user,Course.objects.get(course_title = self.kwargs.get('course_name').replace("_", " ")))
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 156, in totalstat
    tostat = tostat + stat.video + stat.lab
AttributeError: 'TopicStatus' object has no attribute 'video'
[2019-04-13 22:30:35] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topics/ 500 [5.24, 127.0.0.1:44316][0m
[2019-04-13 22:55:58] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [1.15, 127.0.0.1:44880][0m
[2019-04-13 22:56:08] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topics/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 61, in get_context_data
    context['totalstats'] = totalstat(self.request.user,Course.objects.get(course_title = self.kwargs.get('course_name').replace("_", " ")))
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 156, in totalstat
    tostat = tostat + stat.video + stat.lab
AttributeError: 'TopicStatus' object has no attribute 'video'
[2019-04-13 22:56:09] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topics/ 500 [6.03, 127.0.0.1:44880][0m
[2019-04-13 22:57:05] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topics/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 61, in get_context_data
    context['totalstats'] = totalstat(self.request.user,Course.objects.get(course_title = self.kwargs.get('course_name').replace("_", " ")))
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 156, in totalstat
    tostat = tostat + stat.video + stat.lab
AttributeError: 'TopicStatus' object has no attribute 'video'
[2019-04-13 22:57:05] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topics/ 500 [6.33, 127.0.0.1:44880][0m
[2019-04-13 22:58:14] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [3.20, 127.0.0.1:44920][0m
[2019-04-13 22:59:27] INFO [django.channels.server.log_action:141] [mHTTP GET /logout 200 [0.23, 127.0.0.1:44938][0m
[2019-04-13 22:59:28] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/slide1.png 200 [0.02, 127.0.0.1:44938][0m
[2019-04-13 22:59:29] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.11, 127.0.0.1:44938][0m
[2019-04-13 22:59:31] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.11, 127.0.0.1:44938][0m
[2019-04-13 22:59:54] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [0.85, 127.0.0.1:44938][0m
[2019-04-13 22:59:55] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/userinterest 200 [0.24, 127.0.0.1:44938][0m
[2019-04-13 22:59:55] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs//list-bg.png 200 [0.04, 127.0.0.1:44938][0m
[2019-04-13 23:00:26] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [27.28, 127.0.0.1:44938][0m
[2019-04-14 04:30:22] INFO [django.channels.server.log_action:147] [32mHTTP GET /courses/Linux_Fundamentals/topics/ 302 [0.04, 127.0.0.1:45400][0m
[2019-04-14 04:30:22] INFO [django.channels.server.log_action:141] [mHTTP GET /login/?next=/courses/Linux_Fundamentals/topics/ 200 [0.17, 127.0.0.1:45400][0m
[2019-04-14 04:30:37] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/?next=/courses/Linux_Fundamentals/topics/ 302 [1.74, 127.0.0.1:45400][0m
[2019-04-14 04:30:52] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [14.24, 127.0.0.1:45400][0m
[2019-04-14 04:32:04] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/1/ 200 [0.26, 127.0.0.1:45420][0m
[2019-04-14 04:32:31] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/1/ 200 [0.24, 127.0.0.1:45420][0m
[2019-04-14 04:32:37] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:45420][0m
[2019-04-14 04:36:22] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/1/ 200 [0.29, 127.0.0.1:45510][0m
[2019-04-14 04:36:37] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:45510][0m
[2019-04-14 04:56:49] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/(?P<stat>[0-9]+)$']
[2019-04-14 04:56:50] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [1.58, 127.0.0.1:45680][0m
[2019-04-14 04:57:14] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/(?P<stat>[0-9]+)$']
[2019-04-14 04:57:15] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [1.32, 127.0.0.1:45688][0m
[2019-04-14 04:57:46] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 04:57:47] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [1.25, 127.0.0.1:45698][0m
[2019-04-14 04:59:22] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 04:59:23] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [1.30, 127.0.0.1:45712][0m
[2019-04-14 04:59:41] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23,)' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 04:59:42] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.68, 127.0.0.1:45712][0m
[2019-04-14 05:00:11] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:00:12] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [1.26, 127.0.0.1:45718][0m
[2019-04-14 05:01:25] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '', '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:01:25] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.61, 127.0.0.1:45720][0m
[2019-04-14 05:01:33] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:01:34] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.71, 127.0.0.1:45720][0m
[2019-04-14 05:02:02] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '('',)' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:02:02] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.63, 127.0.0.1:45720][0m
[2019-04-14 05:02:29] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:02:29] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [1.34, 127.0.0.1:45730][0m
[2019-04-14 05:03:35] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/1/ 200 [0.23, 127.0.0.1:45732][0m
[2019-04-14 05:03:38] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:45732][0m
[2019-04-14 05:04:11] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '+stat+')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:04:11] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.53, 127.0.0.1:45732][0m
[2019-04-14 05:04:52] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '+stat+')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:04:52] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.73, 127.0.0.1:45732][0m
[2019-04-14 05:05:24] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /courses/Linux_Fundamentals/topic/1/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/Courses/views.py", line 212, in topicdetails
    return render(request, 'courses/topic_detail.html', context)
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'videostat' with arguments '(23, '+stat+')' not found. 1 pattern(s) tried: ['courses\\/videostat\\/(?P<topic>[0-9]+)\\/stat\\/(?P<stat>[0-9]+)$']
[2019-04-14 05:05:25] ERROR [django.channels.server.log_action:154] [35;1mHTTP GET /courses/Linux_Fundamentals/topic/1/ 500 [0.73, 127.0.0.1:45732][0m
[2019-04-14 05:06:43] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/1/ 200 [0.48, 127.0.0.1:45766][0m
[2019-04-14 05:06:47] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:45766][0m
[2019-04-14 05:06:52] INFO [django.channels.server.log_action:141] [mHTTP POST /courses/videostat/23/stat/0 200 [0.59, 127.0.0.1:45766][0m
[2019-04-14 05:07:23] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [7.08, 127.0.0.1:45766][0m
[2019-04-14 05:07:27] INFO [django.channels.server.log_action:141] [mHTTP GET /admin 200 [1.78, 127.0.0.1:45766][0m
[2019-04-14 05:07:28] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:45766][0m
[2019-04-14 05:07:45] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/ 200 [2.20, 127.0.0.1:45766][0m
[2019-04-14 05:07:45] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.04, 127.0.0.1:45786][0m
[2019-04-14 05:07:45] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:45788][0m
[2019-04-14 05:07:45] INFO [django.channels.server.log_action:141] [mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.12, 127.0.0.1:45766][0m
[2019-04-14 05:07:45] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.19, 127.0.0.1:45790][0m
[2019-04-14 05:07:58] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=20 200 [0.78, 127.0.0.1:45790][0m
[2019-04-14 05:07:58] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:45766][0m
[2019-04-14 05:07:58] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.16, 127.0.0.1:45790][0m
[2019-04-14 05:08:17] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/3/change/?_changelist_filters=p%3D20 200 [1.08, 127.0.0.1:45790][0m
[2019-04-14 05:08:17] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:45766][0m
[2019-04-14 05:08:17] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.15, 127.0.0.1:45790][0m
[2019-04-14 05:08:36] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=20 200 [0.91, 127.0.0.1:45790][0m
[2019-04-14 05:10:25] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=20 200 [2.12, 127.0.0.1:45806][0m
[2019-04-14 05:10:25] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:45808][0m
[2019-04-14 05:10:25] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.16, 127.0.0.1:45806][0m
[2019-04-14 05:11:57] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=20 200 [1.97, 127.0.0.1:45810][0m
[2019-04-14 05:11:58] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:45810][0m
[2019-04-14 05:11:58] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:45810][0m
[2019-04-14 05:13:09] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=20 200 [1.93, 127.0.0.1:45814][0m
[2019-04-14 05:13:09] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:45814][0m
[2019-04-14 05:13:09] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/img/search.svg 304 [0.02, 127.0.0.1:45814][0m
[2019-04-14 05:13:09] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.03, 127.0.0.1:45816][0m
[2019-04-14 05:13:21] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?q=admin%40gmail.com 200 [2.34, 127.0.0.1:45816][0m
[2019-04-14 05:13:21] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:45814][0m
[2019-04-14 05:13:22] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.20, 127.0.0.1:45816][0m
[2019-04-14 05:13:39] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=1&q=admin%40gmail.com 200 [1.94, 127.0.0.1:45816][0m
[2019-04-14 05:13:39] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.01, 127.0.0.1:45814][0m
[2019-04-14 05:13:40] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.51, 127.0.0.1:45816][0m
[2019-04-14 05:13:47] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/Courses/topicstatus/?p=2&q=admin%40gmail.com 200 [0.74, 127.0.0.1:45816][0m
[2019-04-14 05:13:47] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/admin/css/fonts.css 304 [0.02, 127.0.0.1:45814][0m
[2019-04-14 05:13:47] INFO [django.channels.server.log_action:141] [mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:45816][0m
[2019-04-14 05:16:09] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/1/ 200 [0.24, 127.0.0.1:45858][0m
[2019-04-14 05:16:21] INFO [django.channels.server.log_action:141] [mHTTP POST /courses/videostat/23/stat/0 200 [0.34, 127.0.0.1:45858][0m
[2019-04-14 05:16:24] INFO [django.channels.server.log_action:141] [mHTTP POST /courses/videostat/23/stat/0 200 [0.36, 127.0.0.1:45858][0m
[2019-04-14 05:16:26] INFO [django.channels.server.log_action:141] [mHTTP POST /courses/videostat/23/stat/1 200 [0.26, 127.0.0.1:45858][0m
[2019-04-14 05:16:37] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [3.36, 127.0.0.1:45858][0m
[2019-04-14 05:17:18] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/3/ 200 [0.22, 127.0.0.1:45858][0m
[2019-04-14 05:17:18] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.02, 127.0.0.1:45858][0m
[2019-04-14 05:17:23] INFO [django.channels.server.log_action:141] [mHTTP POST /courses/videostat/25/stat/0 200 [0.27, 127.0.0.1:45858][0m
[2019-04-14 05:17:32] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topics/ 200 [2.56, 127.0.0.1:45858][0m
[2019-04-14 05:17:32] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.03, 127.0.0.1:45858][0m
[2019-04-14 05:21:02] INFO [django.channels.server.log_action:141] [mHTTP GET /courses/Linux_Fundamentals/topic/3/ 200 [5.65, 127.0.0.1:46084][0m
[2019-04-14 18:16:55] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [2.22, 127.0.0.1:55358][0m
[2019-04-14 18:17:00] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 200 [0.04, 127.0.0.1:55358][0m
[2019-04-14 18:17:02] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.01, 127.0.0.1:55358][0m
[2019-04-14 18:17:05] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.25, 127.0.0.1:55358][0m
[2019-04-14 18:17:09] INFO [django.channels.server.log_action:141] [mHTTP GET /login/ 200 [0.05, 127.0.0.1:55358][0m
[2019-04-14 18:17:10] INFO [django.channels.server.log_action:141] [mHTTP GET /static/home/images/imgback.jpg 200 [0.30, 127.0.0.1:55358][0m
[2019-04-14 18:17:12] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2019-04-14 18:17:12] WARNING [django.channels.server.log_action:149] [33mHTTP GET /favicon.ico 404 [0.08, 127.0.0.1:55358][0m
[2019-04-14 18:17:22] INFO [django.channels.server.log_action:147] [32mHTTP POST /login/ 302 [2.49, 127.0.0.1:55358][0m
[2019-04-14 18:17:22] INFO [django.channels.server.log_action:141] [mHTTP GET / 200 [0.26, 127.0.0.1:55358][0m
[2019-04-14 18:17:29] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.44, 127.0.0.1:55358][0m
[2019-04-14 18:18:58] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/profile/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 604, in workexprofile
    send_mail('Pay Stub verification needed', 'Hello,\n '+request.user.email+' just uploaded is pay stub at: '+link+'.\nPlease review and confirm last verification', settings.EMAIL_HOST_USER, ['mololuwasamuel12@gmail.com'])
  File "/usr/lib/python3.6/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/usr/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[2019-04-14 18:18:58] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/profile/ 500 [61.68, 127.0.0.1:55358][0m
[2019-04-14 18:19:30] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /workexperience/profile/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mololuwa/Desktop/linuxjobber/Django/Linuxjobber/home/views.py", line 604, in workexprofile
    send_mail('Pay Stub verification needed', 'Hello,\n '+request.user.email+' just uploaded is pay stub at: '+link+'.\nPlease review and confirm last verification', settings.EMAIL_HOST_USER, ['mololuwasamuel12@gmail.com'])
  File "/usr/lib/python3.6/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/usr/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[2019-04-14 18:19:30] ERROR [django.channels.server.log_action:154] [35;1mHTTP POST /workexperience/profile/ 500 [20.58, 127.0.0.1:55358][0m
[2019-04-14 18:21:32] INFO [django.channels.server.log_action:147] [32mHTTP POST /workexperience/profile/ 302 [12.19, 127.0.0.1:55444][0m
[2019-04-14 18:21:32] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.33, 127.0.0.1:55444][0m
[2019-04-14 18:29:59] INFO [django.channels.server.log_action:141] [mHTTP GET /media/resume/Screenshot_from_2019-04-11_13-00-39_O38OxMY.png 200 [0.21, 127.0.0.1:55628][0m
[2019-04-14 18:31:34] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.31, 127.0.0.1:55672][0m
[2019-04-14 18:31:35] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/prof1.png 304 [0.01, 127.0.0.1:55672][0m
[2019-04-14 18:31:35] INFO [django.channels.server.log_action:145] [36mHTTP GET /static/home/css/newhomepage/imgs/prof2.png 304 [0.01, 127.0.0.1:55672][0m
[2019-04-14 18:31:37] INFO [django.channels.server.log_action:141] [mHTTP GET /static/favicon.ico 200 [0.02, 127.0.0.1:55672][0m
[2019-04-14 18:33:03] INFO [django.channels.server.log_action:147] [32mHTTP POST /workexperience/profile/ 302 [33.99, 127.0.0.1:55672][0m
[2019-04-14 18:33:03] INFO [django.channels.server.log_action:141] [mHTTP GET /workexperience/profile/ 200 [0.27, 127.0.0.1:55672][0m
